<?php
/**
 * Cities in Canada
 * List generated from http://www.canada-city.ca/all-cities-in-canada.php
 */
global $cities;

$cities['CA'] = array(
	// Alberta
	'AB' => array(
		'Acadia Valley',
		'Acme',
		'Airdrie',
		'Alberta Beach',
		'Alder Flats',
		'Alix',
		'Alliance',
		'Altario',
		'Andrew',
		'Anzac',
		'Ardrossan',
		'Arrowwood',
		'Ashmont',
		'Assumption',
		'Athabasca',
		'Banff',
		'Barons',
		'Barrhead',
		'Bashaw',
		'Bassano',
		'Bawlf',
		'Bear Canyon',
		'Beaumont',
		'Beaverlodge',
		'Beiseker',
		'Bentley',
		'Berwyn',
		'Big Valley',
		'Bindloss',
		'Black Diamond',
		'Blackfalds',
		'Blackie',
		'Blue Ridge',
		'Bon Accord',
		'Bonanza',
		'Bonnyville',
		'Bow Island',
		'Bowden',
		'Boyle',
		'Bragg Creek',
		'Breton',
		'Brocket',
		'Brooks',
		'Brownvale',
		'Bruderheim',
		'Burdett',
		'Byemoor',
		'Cadomin',
		'Calgary',
		'Calling Lake',
		'Calmar',
		'Camrose',
		'Canmore',
		'Carbon',
		'Cardston',
		'Carmangay',
		'Caroline',
		'Carseland',
		'Carstairs',
		'Castor',
		'Cayley',
		'Cereal',
		'Cessford',
		'Champion',
		'Chauvin',
		'Chestermere',
		'Chipewyan Lake',
		'Chipman',
		'Clairmont',
		'Claresholm',
		'Clive',
		'Clyde',
		'Coaldale',
		'Coalhurst',
		'Cochrane',
		'Cold Lake',
		'Conklin',
		'Consort',
		'Coronation',
		'Coutts',
		'Cowley',
		'Craigmyle',
		'Cremona',
		'Crossfield',
		'Crowsnest Pass',
		'Czar',
		'Daysland',
		'DeBolt',
		'Delburne',
		'Delia',
		'Derwent',
		'Devon',
		'Dewberry',
		'Didsbury',
		'Dixonville',
		'Donalda',
		'Donnelly',
		'Drayton Valley',
		'Drumheller',
		'Duchess',
		'Eaglesham',
		'East Coulee',
		'Eckville',
		'Edgerton',
		'Edmonton',
		'Edson',
		'Elk Point',
		'Elkwater',
		'Elnora',
		'Empress',
		'Enchant',
		'Etzikom',
		'Evansburg',
		'Exshaw',
		'Fairview',
		'Falher',
		'Faust',
		'Ferintosh',
		'Flatbush',
		'Foremost',
		'Forestburg',
		'Fort Assiniboine',
		'Fort Chipewyan',
		'Fort MacKay',
		'Fort Macleod',
		'Fort McMurray',
		'Fort Saskatchewan',
		'Fort Vermilion',
		'Fox Creek',
		'Fox Lake',
		'Gadsby',
		'Galahad',
		'Gibbons',
		'Gift Lake',
		'Girouxville',
		'Gleichen',
		'Glendon',
		'Glenwood',
		'Grand Centre',
		'Grande Cache',
		'Grande Prairie',
		'Granum',
		'Grassland',
		'Grassy Lake',
		'Grimshaw',
		'Grouard',
		'Hairy Hill',
		'Halkirk',
		'Hanna',
		'Hardisty',
		'Hay Lakes',
		'Hays',
		'Heinsburg',
		'Heisler',
		'High Level',
		'High Prairie',
		'High River',
		'Hilda',
		'Hines Creek',
		'Hinton',
		'Hobbema',
		'Holden',
		'Hughenden',
		'Hussar',
		'Hythe',
		'Innisfail',
		'Innisfree',
		'Irma',
		'Iron Springs',
		'Irricana',
		'Irvine',
		'Islay',
		'Jarvie',
		'Jasper',
		'Jenner',
		'Joussard',
		'Kananaskis',
		'Keephills',
		'Keg River',
		'Killam',
		'Kinuso',
		'Kitscoty',
		'La Crete',
		'Lac La Biche',
		'Lacombe',
		'Lake Louise',
		'Lamont',
		'Langdon',
		'Lavoy',
		'Leduc',
		'Legal',
		'Leslieville',
		'Lethbridge',
		'Lloydminster',
		'Lodgepole',
		'Lomond',
		'Longview',
		'Lougheed',
		'Ma-Me-O Beach',
		'Magrath',
		'Manning',
		'Mannville',
		'Manyberries',
		'Marlboro',
		'Marwayne',
		'Mayerthorpe',
		'McLennan',
		'Meander River',
		'Medicine Hat',
		'Milk River',
		'Millet',
		'Milo',
		'Minburn',
		'Mirror',
		'Morinville',
		'Morley',
		'Morrin',
		'Mulhurst',
		'Mundare',
		'Myrnam',
		'Namao',
		'Nampa',
		'Nanton',
		'New Dayton',
		'New Norway',
		'New Sarepta',
		'Newbrook',
		'Nisku',
		'Niton Junction',
		'Nobleford',
		'Nordegg',
		'Okotoks',
		'Olds',
		'Onoway',
		'Oyen',
		'Paradise Valley',
		'Peace River',
		'Peerless Lake',
		'Peers',
		'Penhold',
		'Picture Butte',
		'Pincher Creek',
		'Plamondon',
		'Ponoka',
		'Provost',
		'Radway',
		'Rainbow Lake',
		'Ralston',
		'Raymond',
		'Red Deer',
		'Redcliff',
		'Redwater',
		'Rimbey',
		'Robb',
		'Rochester',
		'Rocky Mountain House',
		'Rockyford',
		'Rolling Hills',
		'Rosalind',
		'Rosebud',
		'Rumsey',
		'Rycroft',
		'Ryley',
		'Sangudo',
		'Saskatchewan River Crossing',
		'Schuler',
		'Seba Beach',
		'Sedgewick',
		'Seven Persons',
		'Sexsmith',
		'Sherwood Park',
		'Sibbald',
		'Silver Valley',
		'Slave Lake',
		'Smith',
		'Smoky Lake',
		'Spirit River',
		'Spruce Grove',
		'Spruce View',
		'St. Albert',
		'St. Michael',
		'St. Paul',
		'Stand Off',
		'Standard',
		'Stavely',
		'Stettler',
		'Stirling',
		'Stony Plain',
		'Strathmore',
		'Strome',
		'Sundre',
		'Swan Hills',
		'Sylvan Lake',
		'Taber',
		'Thorhild',
		'Thorsby',
		'Three Hills',
		'Tilley',
		'Tofield',
		'Tomahawk',
		'Torrington',
		'Trochu',
		'Trout Lake',
		'Turner Valley',
		'Two Hills',
		'Valleyview',
		'Vauxhall',
		'Vegreville',
		'Vermilion',
		'Veteran',
		'Viking',
		'Vilna',
		'Vulcan',
		'Wabamun',
		'Wainwright',
		'Walsh',
		'Wandering River',
		'Wanham',
		'Warburg',
		'Warner',
		'Warspite',
		'Waskatenau',
		'Wembley',
		'Westlock',
		'Wetaskiwin',
		'Whitecourt',
		'Whitelaw',
		'Widewater',
		'Wildwood',
		'Willingdon',
		'Winfield',
		'Woking',
		'Worsley',
		'Wrentham',
		'Youngstown'
	),
	// British Columbia
	'BC' => array(
		'100 Mile House',
		'108 Mile House',
		'108 Mile Ranch',
		'150 Mile House',
		'Abbotsford',
		'Agassiz',
		'Ahousat',
		'Aldergrove',
		'Alert Bay',
		'Alexis Creek',
		'Alkali Lake',
		'Armstrong',
		'Ashcroft',
		'Atlin',
		'Avola',
		'Balfour',
		'Bamfield',
		'Barriere',
		'Beach Grove',
		'Bear Lake',
		'Beaver Cove',
		'Beaverdell',
		'Bella Bella',
		'Bella Coola',
		'Black Creek',
		'Black Point',
		'Blue River',
		'Bob Quinn Lake',
		'Boston Bar',
		'Boswell',
		'Bowen Island',
		'Bowser',
		'Bridge Lake',
		'Britannia Beach',
		'Burnaby',
		'Burns Lake',
		'Cache Creek',
		'Campbell River',
		'Canal Flats',
		'Cassiar',
		'Castlegar',
		'Celista',
		'Chase',
		'Chemainus',
		'Chetwynd',
		'Chilliwack',
		'Christina Lake',
		'Clearwater',
		'Clinton',
		'Cobble Hill',
		'Colwood',
		'Comox',
		'Coquitlam',
		'Courtenay',
		'Cowichan Bay',
		'Cranbrook',
		'Crawford Bay',
		'Crescent Beach',
		'Creston',
		'Cumberland',
		'Dawson Creek',
		'Dease Lake',
		'Delta',
		'Donald',
		'Douglas Lake',
		'Duncan',
		'Dunster',
		'D\'Arcy',
		'East Pine',
		'Elkford',
		'Elko',
		'Enderby',
		'Estevan Point',
		'Fairmont Hot Springs',
		'Falkland',
		'Fauquier',
		'Fernie',
		'Field',
		'Flatrock',
		'Forest Grove',
		'Fort Fraser',
		'Fort Nelson',
		'Fort St. James',
		'Fort St. John',
		'Fraser Lake',
		'Fruitvale',
		'Gabriola',
		'Galiano Island',
		'Ganges',
		'Gibsons',
		'Giscome',
		'Gold Bridge',
		'Gold River',
		'Golden',
		'Good Hope Lake',
		'Grand Forks',
		'Granisle',
		'Grasmere',
		'Grassy Plains',
		'Greenville',
		'Greenwood',
		'Hartley Bay',
		'Hazelton',
		'Hedley',
		'Hemlock Valley',
		'Hendrix Lake',
		'Hixon',
		'Holberg',
		'Hope',
		'Horsefly',
		'Houston',
		'Hudson\'s Hope',
		'Invermere',
		'Iskut',
		'Jaffray',
		'Kamloops',
		'Kaslo',
		'Kelowna',
		'Kemano',
		'Keremeos',
		'Kimberley',
		'Kincolith',
		'Kitimat',
		'Kitkatla',
		'Kitsault',
		'Kitwanga',
		'Klemtu',
		'Kyuquot',
		'Lac la Hache',
		'Ladysmith',
		'Lake Cowichan',
		'Langara',
		'Langley',
		'Lantzville',
		'Likely',
		'Lillooet',
		'Little Fort',
		'Logan Lake',
		'Loos',
		'Lower Post',
		'Lumby',
		'Lytton',
		'Mackenzie',
		'Maple Ridge',
		'Masset',
		'McBride',
		'McLeese Lake',
		'McLeod Lake',
		'Merritt',
		'Mica Creek',
		'Midway',
		'Mission',
		'Montney',
		'Moyie',
		'Muncho Lake',
		'Nakusp',
		'Nanaimo',
		'Naramata',
		'Nelson',
		'New Aiyansh',
		'New Denver',
		'New Westminster',
		'Nimpo Lake',
		'North Saanich',
		'North Vancouver',
		'Ocean Falls',
		'Ocean Park',
		'Okanagan Falls',
		'Oliver',
		'Osoyoos',
		'Oyama',
		'Parksville',
		'Parson',
		'Peachland',
		'Pemberton',
		'Penticton',
		'Pitt Meadows',
		'Port Alberni',
		'Port Alice',
		'Port Clements',
		'Port Coquitlam',
		'Port Edward',
		'Port Hardy',
		'Port McNeill',
		'Port Mellon',
		'Port Moody',
		'Port Renfrew',
		'Pouce Coupe',
		'Powell River',
		'Prespatou',
		'Prince George',
		'Prince Rupert',
		'Princeton',
		'Prophet River',
		'Quadra Island',
		'Qualicum Beach',
		'Queen Charlotte',
		'Quesnel',
		'Radium Hot Springs',
		'Red Rock',
		'Revelstoke',
		'Richmond',
		'Riondel',
		'Riske Creek',
		'Rock Creek',
		'Rolla',
		'Rossland',
		'Saanich',
		'Salmo',
		'Salmon Arm',
		'Salmon Valley',
		'Sandspit',
		'Savona',
		'Sayward',
		'Sechelt',
		'Shalalth',
		'Sicamous',
		'Sidney',
		'Skookumchuck',
		'Slocan',
		'Smithers',
		'Sointula',
		'Sooke',
		'Sorrento',
		'South Slocan',
		'Sparwood',
		'Spences Bridge',
		'Spillimacheen',
		'Squamish',
		'Stewart',
		'Summerland',
		'Summit Lake',
		'Surrey',
		'Tachie',
		'Tahsis',
		'Tatla Lake',
		'Taylor',
		'Telegraph Creek',
		'Telkwa',
		'Terrace',
		'Thrums',
		'Toad River',
		'Tofino',
		'Topley',
		'Trail',
		'Trout Lake',
		'Tsay Keh Dene',
		'Tumbler Ridge',
		'Ucluelet',
		'Valemount',
		'Vallican',
		'Van Anda',
		'Vancouver',
		'Vanderhoof',
		'Vavenby',
		'Vernon',
		'Victoria',
		'View Royal',
		'Wells',
		'West Vancouver',
		'Westbank',
		'Westwold',
		'Whistler',
		'White Rock',
		'Williams Lake',
		'Willowbrook',
		'Winfield',
		'Winter Harbour',
		'Wonowon',
		'Wynndel',
		'Yahk',
		'Yale',
		'Youbou',
		'Zeballos'
	),
	// Manitoba
	'MB' => array(
		'Agassiz Provincial Forest',
		'Alexander',
		'Alonsa',
		'Altona',
		'Arborg',
		'Ashern',
		'Austin',
		'Baldur',
		'Basswood',
		'Beausejour',
		'Belmont',
		'Benito',
		'Berens River',
		'Beulah',
		'Binscarth',
		'Birtle',
		'Bissett',
		'Boissevain',
		'Brandon',
		'Brochet',
		'Brookdale',
		'Camperville',
		'Carberry',
		'Carman',
		'Cartwright',
		'Churchill',
		'Cormorant',
		'Cowan',
		'Cranberry Portage',
		'Crandall',
		'Cross Lake',
		'Crystal City',
		'Cypress River',
		'Darlingford',
		'Dauphin',
		'Deloraine',
		'Dominion City',
		'Dugald',
		'Easterville',
		'Eddystone',
		'Edwin',
		'Elgin',
		'Elie',
		'Elkhorn',
		'Elm Creek',
		'Emerson',
		'Erickson',
		'Eriksdale',
		'Ethelbert',
		'Falcon Lake',
		'Fisher Branch',
		'Fisher River',
		'Flin Flon',
		'Fork River',
		'Foxwarren',
		'Gilbert Plains',
		'Gillam',
		'Gimli',
		'Gladstone',
		'Glenboro',
		'Glenella',
		'Gods Lake Narrows',
		'Grand Beach',
		'Grand Rapids',
		'Grandview',
		'Gretna',
		'Gypsumville',
		'Hadashville',
		'Hamiota',
		'Hartney',
		'Hecla',
		'Holland',
		'Ilford',
		'Inwood',
		'Island Lake',
		'Kelwood',
		'Kenton',
		'Killarney',
		'La Broquerie',
		'Lac Brochet',
		'Lac du Bonnet',
		'Langruth',
		'Leaf Rapids',
		'Libau',
		'Little Grand Rapids',
		'Lockport',
		'Lundar',
		'Lynn Lake',
		'MacGregor',
		'Mafeking',
		'Manigotagan',
		'Manitou',
		'McAuley',
		'McCreary',
		'Melita',
		'Miami',
		'Miniota',
		'Minnedosa',
		'Minto',
		'Moose Lake',
		'Morden',
		'Morris',
		'Neepawa',
		'Nelson House',
		'Newdale',
		'Niverville',
		'Norway House',
		'Notre Dame de Lourdes',
		'Oak Lake',
		'Oak River',
		'Oakville',
		'Ochre River',
		'Oxford House',
		'Peguis',
		'Pelican Rapids',
		'Pikwitonei',
		'Pilot Mound',
		'Pinawa',
		'Pine Dock',
		'Pine Falls',
		'Pine River',
		'Piney',
		'Plum Coulee',
		'Plumas',
		'Pointe du Bois',
		'Poplar River',
		'Poplarfield',
		'Portage la Prairie',
		'Rapid City',
		'Rathwell',
		'Red Sucker Lake',
		'Rennie',
		'Reston',
		'Rivers',
		'Riverton',
		'Roblin',
		'Roland',
		'Rorketon',
		'Rossburn',
		'Russell',
		'Sandy Lake',
		'Sanford',
		'Selkirk',
		'Shamattawa',
		'Shilo',
		'Shoal Lake',
		'Sidney',
		'Sifton',
		'Snow Lake',
		'Snowflake',
		'Somerset',
		'Souris',
		'South Indian Lake',
		'Sperling',
		'Split Lake',
		'Sprague',
		'St-Pierre-Jolys',
		'St. Claude',
		'St. Francois Xavier',
		'St. Jean Baptiste',
		'St. Laurent',
		'St. Lazare',
		'Starbuck',
		'Ste. Agathe',
		'Ste. Rose du Lac',
		'Steep Rock',
		'Steinbach',
		'Stonewall',
		'Strathclair',
		'Swan Lake',
		'Swan River',
		'Tadoule Lake',
		'Teulon',
		'The Pas',
		'Thicket Portage',
		'Thompson',
		'Treherne',
		'Virden',
		'Vita',
		'Waasagomach',
		'Wabowden',
		'Wanless',
		'Wasagaming',
		'Waterhen',
		'Wawanesa',
		'Whitemouth',
		'Winkler',
		'Winnipeg',
		'Winnipeg Beach',
		'Winnipegosis',
		'Woodridge'
	),
	// New Brunswick
	'NB' => array(
		'Albert',
		'Albert Mines',
		'Allardville',
		'Alma',
		'Baie-Ste-Anne',
		'Baker Brook',
		'Balmoral',
		'Bath',
		'Bathurst',
		'Belledune',
		'Beresford',
		'Blacks Harbour',
		'Blackville',
		'Boiestown',
		'Bouctouche',
		'Browns Flat',
		'Campbellton',
		'Campobello Island',
		'Canterbury',
		'Cap-Pele',
		'Caraquet',
		'Centreville',
		'Chatham',
		'Chipman',
		'Clair',
		'Clarks Corners',
		'Cocagne',
		'Dalhousie',
		'Debec',
		'Dieppe',
		'Doaktown',
		'Dorchester',
		'Edmundston',
		'Florenceville',
		'Fords Mills',
		'Fredericton',
		'Fredericton Junction',
		'Gagetown',
		'Glassville',
		'Grand Bay',
		'Grand Falls',
		'Grand Manan',
		'Grand-Sault',
		'Grande-Anse',
		'Hampstead',
		'Hampton',
		'Harewood',
		'Hartland',
		'Havelock',
		'Hillsborough',
		'Hoyt',
		'Jacquet River',
		'Kedgwick',
		'Keswick',
		'Lameque',
		'Maces Bay',
		'McAdam',
		'Meductic',
		'Memramcook',
		'Millville',
		'Minto',
		'Miramichi',
		'Miscou Island',
		'Moncton',
		'Nackawic',
		'Neguac',
		'New Denmark',
		'Norton',
		'Oromocto',
		'Paquetville',
		'Perth-Andover',
		'Petit Rocher',
		'Petitcodiac',
		'Plaster Rock',
		'Port Elgin',
		'Quispamsis',
		'Red Bank',
		'Richibucto',
		'Riverview',
		'Rogersville',
		'Rothesay',
		'Sackville',
		'Saint Andrews',
		'Saint John',
		'Salisbury',
		'Shediac',
		'Shippagan',
		'Springfield',
		'St-Antoine',
		'St-Basile',
		'St-Isidore',
		'St-Louis de Kent',
		'St-Quentin',
		'St. George',
		'St. Leonard',
		'St. Martins',
		'St. Stephen',
		'Stanley',
		'Ste-Anne-de-Madawaska',
		'Summerville',
		'Sussex',
		'Tabusintac',
		'Tobique First Nation',
		'Tracadie-Sheila',
		'Welsford',
		'Westfield',
		'Woodstock',
		'Young\'s Cove Road'
	),
	// Newfoundland and Labrador
	'NL' => array(
		'Appleton',
		'Argentia',
		'Arnold\'s Cove',
		'Avondale',
		'Badger',
		'Baie Verte',
		'Batteau',
		'Battle Harbour',
		'Bauline',
		'Bay Bulls',
		'Bay de Verde',
		'Bay L\'Argent',
		'Bay Roberts',
		'Beaumont',
		'Bell Island',
		'Belleoram',
		'Bellevue',
		'Benoit\'s Cove',
		'Birchy Bay',
		'Bishop\'s Falls',
		'Black Duck Cove',
		'Black Tickle',
		'Bonavista',
		'Botwood',
		'Boyd\'s Cove',
		'Branch',
		'Brent\'s Cove',
		'Brigus',
		'Buchans',
		'Burgeo',
		'Burin',
		'Burlington',
		'Burnt Islands',
		'Campbellton',
		'Cape Broyle',
		'Carbonear',
		'Carmanville',
		'Cartwright',
		'Catalina',
		'Centreville-Wareham-Trinity',
		'Chance Cove',
		'Change islands',
		'Chapel Arm',
		'Charlottetown',
		'Churchill Falls',
		'Clarenville',
		'Clarenville-Shoal Harbour',
		'Clarke\'s Beach',
		'Codroy',
		'Colliers',
		'Come By Chance',
		'Comfort Cove-Newstead',
		'Conception Bay South',
		'Conception Harbour',
		'Conche',
		'Conne River',
		'Cook\'s Harbour',
		'Corner Brook',
		'Cottlesville',
		'Cow Head',
		'Cupids',
		'Daniel\'s Harbour',
		'Davis Inlet',
		'Deer Lake',
		'Dover',
		'Eastport',
		'Elliston',
		'Embree',
		'Englee',
		'English Harbour East',
		'Fair Haven',
		'Fermeuse',
		'Flatrock',
		'Fleur de Lys',
		'Flower\'s Cove',
		'Fogo',
		'Forteau',
		'Fortune',
		'Fox Cove-Mortier',
		'Frenchmans Island',
		'Freshwater',
		'Gambo',
		'Gander',
		'Garnish',
		'Gaultois',
		'Glenwood',
		'Glovertown',
		'Goose Bay',
		'Grand Bank',
		'Grand Falls',
		'Grand Falls-Windsor',
		'Great Harbour Deep',
		'Green Island Cove',
		'Greenspond',
		'Hampden',
		'Hant\'s Harbour',
		'Happy Valley-Goose Bay',
		'Harbour Breton',
		'Harbour Grace',
		'Harbour Main-Chapel Cove-Lakev',
		'Hare Bay',
		'Hawke\'s Bay',
		'Heart\'s Content',
		'Heart\'s Delight-Islington',
		'Heart\'s Desire',
		'Hickman\'s Harbour',
		'Hillgrade',
		'Hillview',
		'Holyrood',
		'Hopedale',
		'Howley',
		'Humber Arm South',
		'Indian Tickle',
		'Island Harbour',
		'Isle aux Morts',
		'Jackson\'s Arm',
		'Jamestown',
		'Joe Batt\'s Arm-Barr\'d Islands-',
		'King\'s Cove',
		'King\'s Point',
		'Kippens',
		'La Scie',
		'Labrador City',
		'Ladle Cove',
		'Lamaline',
		'Lark Harbour',
		'Lawn',
		'Lewisporte',
		'Little Bay',
		'Little Bay Islands',
		'Little Burnt Bay',
		'Little Catalina',
		'Little Heart\'s Ease',
		'Logy Bay-Middle Cove-Outer Cove',
		'Long Harbour-Mount Arlington Heights',
		'Long Pond',
		'Lourdes',
		'Lower Island Cove',
		'Lumsden',
		'L\'Anse-au-Loup',
		'Main Brook',
		'Makkovik',
		'Marystown',
		'Mary\'s Harbour',
		'Massey Drive',
		'McIver\'s',
		'Millertown',
		'Milltown-Head of Bay D\'Espoir',
		'Ming\'s Bight',
		'Monkstown',
		'Mount Carmel-Mitchells Brook-S',
		'Mount Moriah',
		'Mount Pearl',
		'Musgrave Harbour',
		'Musgravetown',
		'Nain',
		'New Harbour',
		'New Perlican',
		'New-Wes-Valley',
		'Nippers Harbour',
		'Norman\'s Cove-Long Cove',
		'Norris Arm',
		'North West River',
		'Northern Arm',
		'Old Perlican',
		'Packs Harbour',
		'Pacquet',
		'Paradise',
		'Paradise River',
		'Pasadena',
		'Peterview',
		'Petty Harbour-Maddox Cove',
		'Placentia',
		'Plate Cove East',
		'Point Leamington',
		'Pool\'s Cove',
		'Port au Choix',
		'Port au Port West-Aguathuna-Fe',
		'Port Aux Basques',
		'Port Blandford',
		'Port Hope Simpson',
		'Port Rexton',
		'Port Saunders',
		'Port Union',
		'Portugal Cove-St. Philip\'s',
		'Postville',
		'Pouch Cove',
		'Princeton',
		'Raleigh',
		'Ramea',
		'Red Bay',
		'Reefs Harbour',
		'Rencontre East',
		'Rigolet',
		'River of Ponds',
		'Robert\'s Arm',
		'Rocky Harbour',
		'Roddickton',
		'Rose Blanche-Harbour Le Cou',
		'Rushoon',
		'Salmon Cove',
		'Salvage',
		'Seal Cove',
		'Seldom-Little Seldom',
		'Small Point-Broad Cove-Blackhe',
		'South Brook',
		'South River',
		'Southern Harbour',
		'Spaniard\'s Bay',
		'Spotted Island',
		'Springdale',
		'St. Alban\'s',
		'St. Anthony',
		'St. Bernard\'s-Jacques Fontaine',
		'St. Brendan\'s',
		'St. Bride\'s',
		'St. George\'s',
		'St. Jacques-Coomb\'s Cove',
		'St. John\'s',
		'St. Lawrence',
		'St. Lewis',
		'St. Lunaire-Griquet',
		'St. Mary\'s',
		'St. Vincent\'s-St. Stephen\'s-Pe',
		'Steady Brook',
		'Stephenville',
		'Stephenville Crossing',
		'Summerford',
		'Summerside',
		'Sunnyside',
		'Terra Nova',
		'Terrenceville',
		'Torbay',
		'Trepassey',
		'Triton',
		'Trout River',
		'Twillingate',
		'Upper Island Cove',
		'Victoria',
		'Wabana',
		'Wabush',
		'Wesleyville',
		'Western Bay',
		'Westport',
		'Whitbourne',
		'Winterton',
		'Witless Bay',
		'Woody Point'
	),
	// Northwest Territories
	'NT' => array(
		'Aklavik',
		'Edzo',
		'Enterprise',
		'Fort Good Hope',
		'Fort Liard',
		'Fort McPherson',
		'Fort Providence',
		'Fort Simpson',
		'Fort Smith',
		'Hay River',
		'Inuvik',
		'Jean Marie River',
		'Kakisa',
		'Kugluktuk',
		'Nahanni Butte',
		'Norman Wells',
		'Rae',
		'Rae Lakes',
		'Trout Lake',
		'Tsiigehtchic',
		'Tuktoyaktuk',
		'Wrigley',
		'Yellowknife'
	),
	// Nova Scotia
	'NS' => array(
		'Advocate Harbour',
		'Amherst',
		'Annapolis Royal',
		'Antigonish',
		'Argyle',
		'Arichat',
		'Aylesford',
		'Baddeck',
		'Bass River',
		'Bear River',
		'Berwick',
		'Blandford',
		'Boisdale',
		'Boularderie',
		'Bridgetown',
		'Bridgewater',
		'Brookfield',
		'Canning',
		'Canso',
		'Caribou',
		'Carleton',
		'Chelsea',
		'Chester',
		'Cheticamp',
		'Cheverie',
		'Clarksville',
		'Clark\'s Harbour',
		'Collingwood Corner',
		'Dartmouth',
		'Debert',
		'Digby',
		'Dingwall',
		'Dundee',
		'East Bay',
		'Ecum Secum',
		'Elmsdale',
		'Eskasoni',
		'Freeport',
		'French Village',
		'Gabarus',
		'Glace Bay',
		'Goldboro',
		'Goshen',
		'Grand Etang',
		'Grand Lake',
		'Grand Narrows',
		'Great Village',
		'Greenwood',
		'Guysborough',
		'Halifax',
		'Hantsport',
		'Heatherton',
		'Hopewell',
		'Hubbards',
		'Ingonish',
		'Inverness',
		'Kennetcook',
		'Kentville',
		'Kenzieville',
		'Ketch Harbour',
		'Kingston',
		'LaHave',
		'Lake Charlotte',
		'Larrys River',
		'Lawrencetown',
		'Liverpool',
		'Lockeport',
		'Louisbourg',
		'Louisdale',
		'Lunenburg',
		'L\'Ardoise',
		'Mabou',
		'Maccan',
		'Mahone Bay',
		'Maitland',
		'Margaree Forks',
		'Marion Bridge',
		'Melrose',
		'Merigomish',
		'Meteghan',
		'Middleton',
		'Monastery',
		'Mount Uniacke',
		'Mulgrave',
		'Musquodoboit Harbour',
		'New Germany',
		'New Glasgow',
		'New Ross',
		'New Waterford',
		'Noel',
		'North Sydney',
		'Oxford',
		'Parrsboro',
		'Peggy\'s Cove',
		'Pictou',
		'Port Bickerton',
		'Port Dufferin',
		'Port Greville',
		'Port Hawkesbury',
		'Port Hood',
		'Port La Tour',
		'Port Maitland',
		'Port Morien',
		'Port Mouton',
		'Pubnico',
		'Pugwash',
		'Queensport',
		'River Hebert',
		'River John',
		'Riverport',
		'Salt Springs',
		'Saulnierville',
		'Shelburne',
		'Sherbrooke',
		'Shubenacadie',
		'Southampton',
		'Springfield',
		'Springhill',
		'St. Margaret Village',
		'St. Peter\'s',
		'Stellarton',
		'Stewiacke',
		'Sydney',
		'Tangier',
		'Tatamagouche',
		'Thorburn',
		'Trenton',
		'Truro',
		'Tusket',
		'Upper Musquodoboit',
		'Upper Stewiacke',
		'Wallace',
		'Walton',
		'Waverley',
		'Wedgeport',
		'Westville',
		'Weymouth',
		'Whycocomagh',
		'Windsor',
		'Wolfville',
		'Yarmouth'
	),
	// Nunavut
	'NU' => array(
		'Arviat',
		'Baker Lake',
		'Cambridge Bay',
		'Cape Dorset',
		'Chesterfield Inlet',
		'Coral Harbour',
		'Gjoa Haven',
		'Iqaluit',
		'Rankin Inlet',
		'Resolute',
		'Whale Cove'
	),
	// Ontario
	'ON' => array(
		'Aberarder',
		'Abitibi Canyon',
		'Acton',
		'Adolphustown',
		'Ailsa Craig',
		'Ajax',
		'Alban',
		'Alderville First Nation',
		'Alexandria',
		'Alfred',
		'Algoma Mills',
		'Alliston',
		'Almonte',
		'Alvinston',
		'Amherstburg',
		'Ancaster',
		'Angus',
		'Apsley',
		'Arden',
		'Arkell',
		'Arkona',
		'Armstrong',
		'Arnprior',
		'Arthur',
		'Athens',
		'Atikokan',
		'Attawapiskat',
		'Atwood',
		'Auburn',
		'Aurora',
		'Avonmore',
		'Aylmer',
		'Ayr',
		'Ayton',
		'Azilda',
		'Baden',
		'Bailieboro',
		'Bala',
		'Balmertown',
		'Baltimore',
		'Bancroft',
		'Barrie',
		'Barry\'s Bay',
		'Barwick',
		'Batawa',
		'Batchawana Bay',
		'Bath',
		'Bayfield',
		'Baysville',
		'Beachburg',
		'Beachville',
		'Beamsville',
		'Beardmore',
		'Bearskin Lake',
		'Bearskin Lake First Nation',
		'Bear\'s Passage',
		'Beaverton',
		'Beeton',
		'Belle River',
		'Belleville',
		'Belmont',
		'Bethany',
		'Bethesda',
		'Big Trout Lake',
		'Binbrook',
		'Birch Island',
		'Biscotasing',
		'Blackstock',
		'Blenheim',
		'Blezard Valley',
		'Blind River',
		'Bloomfield',
		'Blyth',
		'Bobcaygeon',
		'Bolton',
		'Bonfield',
		'Borden',
		'Bothwell',
		'Bourget',
		'Bowmanville',
		'Bracebridge',
		'Bradford',
		'Bradford West Gwillimbury',
		'Braeside',
		'Brampton',
		'Brantford',
		'Brechin',
		'Breslau',
		'Bridgenorth',
		'Brigden',
		'Bright',
		'Brighton',
		'Brights Grove',
		'Britt',
		'Brockville',
		'Brooklin',
		'Brownsville',
		'Bruce Mines',
		'Brussels',
		'Buckhorn',
		'Burford',
		'Burgessville',
		'Burk\'s Falls',
		'Burleigh Falls',
		'Burlington',
		'Cache Bay',
		'Calabogie',
		'Caledon',
		'Caledon East',
		'Caledonia',
		'Callander',
		'Calstock',
		'Cambray',
		'Cambridge',
		'Cameron',
		'Camlachie',
		'Campbellford',
		'Campbellville',
		'Cannington',
		'Capreol',
		'Caradoc First Nation',
		'Caramat',
		'Cardiff',
		'Cardinal',
		'Cargill',
		'Carleton Place',
		'Carnarvon',
		'Carp',
		'Cartier',
		'Casselman',
		'Castlemore',
		'Castleton',
		'Cat Lake',
		'Cavan',
		'Cayuga',
		'Centralia',
		'Chalk River',
		'Chapleau',
		'Charlton',
		'Chatham',
		'Chatsworth',
		'Chelmsford',
		'Chesley',
		'Chesterville',
		'Chiefs Point First Nation',
		'Chippewas of Kettle/Stony Poin',
		'Chippewas Of Sarnia First Nati',
		'Christian Island',
		'Claremont',
		'Clarence Creek',
		'Clarence-Rockland',
		'Clarington',
		'Clarkson',
		'Clearwater Bay',
		'Clifford',
		'Clinton',
		'Cloud Bay',
		'Cobalt',
		'Cobden',
		'Coboconk',
		'Cobourg',
		'Cochenour',
		'Cochrane',
		'Coe Hill',
		'Colborne',
		'Colchester',
		'Cold Springs',
		'Coldwater',
		'Collingwood',
		'Comber',
		'Concord',
		'Coniston',
		'Connaught',
		'Constance Bay',
		'Constance Lake First Nation',
		'Cookstown',
		'Cooksville',
		'Cornwall',
		'Corunna',
		'Cottam',
		'Courtice',
		'Courtright',
		'Crediton',
		'Creemore',
		'Crysler',
		'Crystal Beach',
		'Cumberland',
		'Dashwood',
		'Deep River',
		'Deer Lake',
		'Deerbrook',
		'Delaware of the Thames(Moravia',
		'Delhi',
		'Delta',
		'Denbigh',
		'Desbarats',
		'Deseronto',
		'Deux-Rivieres',
		'Devlin',
		'Dokis',
		'Dokis First Nation',
		'Dorchester',
		'Dorion',
		'Dorset',
		'Douglas',
		'Douglastown',
		'Drayton',
		'Dresden',
		'Drumbo',
		'Dryden',
		'Dublin',
		'Dubreuilville',
		'Dunchurch',
		'Dundalk',
		'Dundas',
		'Dungannon',
		'Dunnville',
		'Dunsford',
		'Durham',
		'Dutton',
		'Dwight',
		'Dyer\'s Bay',
		'Eagle Lake First Nation',
		'Eagle River',
		'Ear Falls',
		'Earlton',
		'East Gwillimbury',
		'East York',
		'Eastwood',
		'Echo Bay',
		'Eganville',
		'Elgin',
		'Elizabethtown',
		'Elk Lake',
		'Elliot Lake',
		'Elmira',
		'Elmvale',
		'Elora',
		'Embro',
		'Embrun',
		'Emeryville',
		'Emo',
		'Emsdale',
		'Englehart',
		'Enterprise',
		'Erin',
		'Espanola',
		'Essex',
		'Estaire',
		'Etobicoke',
		'Eugenia',
		'Exeter',
		'Fauquier',
		'Fenelon Falls',
		'Fenwick',
		'Fergus',
		'Feversham',
		'Field',
		'Finch',
		'Fingal',
		'Fisherville',
		'Flamborough',
		'Flanders',
		'Flesherton',
		'Foley',
		'Foleyet',
		'Forest',
		'Fort Albany',
		'Fort Erie',
		'Fort Frances',
		'Fort Hope',
		'Fort Severn',
		'Fort Severn First Nation',
		'Fort William First Nation',
		'Foxboro',
		'Foymount',
		'Frankford',
		'Freelton',
		'French River First Nation',
		'Galt',
		'Gananoque',
		'Garden Hill',
		'Garden River First Nation',
		'Garson',
		'Georgetown',
		'Georgina',
		'Geraldton',
		'Gilmour',
		'Glen Robertson',
		'Glen Water',
		'Glen Williams',
		'Glencoe',
		'Gloucester',
		'Goderich',
		'Gogama',
		'Golden Lake',
		'Gooderham',
		'Gore Bay',
		'Gormley',
		'Gorrie',
		'Goulais River',
		'Gowganda',
		'Grafton',
		'Grand Bend',
		'Grand Valley',
		'Granton',
		'Grassy Narrows',
		'Grassy Narrows First Nation',
		'Gravenhurst',
		'Greensville',
		'Grimsby',
		'Guelph',
		'Gull Bay',
		'Gull Bay First Nation',
		'Hagersville',
		'Haileybury',
		'Haldimand',
		'Haliburton',
		'Halton Hills',
		'Hamilton',
		'Hampton',
		'Hanmer',
		'Hanover',
		'Harrietsville',
		'Harriston',
		'Harrow',
		'Harrowsmith',
		'Hastings',
		'Havelock',
		'Hawk Junction',
		'Hawkesbury',
		'Hearst',
		'Hemlo',
		'Hensall',
		'Henvey Inlet First Nation',
		'Hepworth',
		'Hespeler',
		'Hickson',
		'Highgate',
		'Hillsburgh',
		'Holland Landing',
		'Holstein',
		'Honey Harbour',
		'Hornepayne',
		'Hudson',
		'Humphrey',
		'Huntsville',
		'Ignace',
		'Ilderton',
		'Ingersoll',
		'Ingleside',
		'Innerkip',
		'Innisfil',
		'Inverary',
		'Inwood',
		'Iron Bridge',
		'Iroquois',
		'Iroquois Falls',
		'Jaffray Melick',
		'Jarvis',
		'Jasper',
		'Jellicoe',
		'Jockvale',
		'Johnstown',
		'Jordan',
		'Kaministiquia',
		'Kamiskotia',
		'Kanata',
		'Kapuskasing',
		'Kasabonika First Nation',
		'Kashechewan First Nation',
		'Kearney',
		'Keene',
		'Keewatin',
		'Kemptville',
		'Kenora',
		'Kent Centre',
		'Kerwood',
		'Keswick',
		'Killaloe',
		'Killarney',
		'Kincardine',
		'King City',
		'Kingfisher Lake',
		'Kingfisher Lake First Nation',
		'Kingston',
		'Kingsville',
		'Kinmount',
		'Kintore',
		'Kirkfield',
		'Kirkland Lake',
		'Kirkton',
		'Kitchener',
		'Kleinburg',
		'Lac la Croix',
		'Lac Seul First Nation',
		'Lafontaine',
		'Lagoon City',
		'Lakefield',
		'Lambeth',
		'Lanark',
		'Lancaster',
		'Langton',
		'Lansdowne',
		'Lansdowne House',
		'Larder Lake',
		'LaSalle',
		'Latchford',
		'Leamington',
		'Lefroy',
		'Levack',
		'Lincoln',
		'Lindsay',
		'Linwood',
		'Lion\'s Head',
		'Listowel',
		'Little Britain',
		'Little Current',
		'Lively',
		'Lombardy',
		'London',
		'Long Lac',
		'Long Lake First Nation',
		'Long Point',
		'Long Sault',
		'Longlac',
		'Lorne',
		'Lucan',
		'Lucknow',
		'Lyn',
		'Lynden',
		'L\'Orignal',
		'Maberly',
		'Macdiarmid',
		'MacTier',
		'Madoc',
		'Madsen',
		'Magnetawan',
		'Magnetawan First Nation',
		'Maidstone',
		'Maitland',
		'Mallorytown',
		'Malton',
		'Manitouwadge',
		'Manitowaning',
		'Manotick',
		'Maple',
		'Marathon',
		'Markdale',
		'Markham',
		'Markstay',
		'Marmora',
		'Marten Falls First Nation',
		'Marten River',
		'Martintown',
		'Massey',
		'Matachewan',
		'Matheson',
		'Mattawa',
		'Mattice',
		'Maxville',
		'Maynooth',
		'McDonalds Corners',
		'McGregor',
		'McKellar',
		'Meaford',
		'Melbourne',
		'Merlin',
		'Merrickville',
		'Metcalfe',
		'Midland',
		'Mildmay',
		'Milford Bay',
		'Millbrook',
		'Millhaven',
		'Milton',
		'Milverton',
		'Minaki',
		'Mindemoya',
		'Minden',
		'Mine Centre',
		'Missanabie',
		'Mississauga',
		'Mitchell',
		'Mohawks Of The Bay of Quinte F',
		'Monkton',
		'Moonbeam',
		'Moonstone',
		'Mooretown',
		'Moose Creek',
		'Moose Factory',
		'Moosonee',
		'Morrisburg',
		'Morson',
		'Mount Albert',
		'Mount Brydges',
		'Mount Forest',
		'Mount Hope',
		'Mount Pleasant',
		'Muskoka',
		'Muskoka Falls',
		'Muskrat Dam',
		'Muskrat Dam First Nation',
		'M\'Chigeeng',
		'Nairn',
		'Naiscoutaing First Nation',
		'Nakina',
		'Nanticoke',
		'Napanee',
		'Navan',
		'Nepean',
		'Nephton',
		'Nestor Falls',
		'Neustadt',
		'New Dundee',
		'New Hamburg',
		'New Liskeard',
		'New Tecumseth',
		'Newburgh',
		'Newcastle',
		'Newmarket',
		'Newtonville',
		'Niagara Falls',
		'Niagara-on-the-Lake',
		'Nickel Centre',
		'Nipigon',
		'Nipissing First Nation',
		'Nobel',
		'Nobleton',
		'Noelville',
		'North Augusta',
		'North Bay',
		'North Gower',
		'North Spirit Lake',
		'North York',
		'Northbrook',
		'Norval',
		'Norwich',
		'Norwood',
		'Oak Ridges',
		'Oakville',
		'Oakwood',
		'Oba',
		'Odessa',
		'Ogoki',
		'Ohsweken',
		'Oil Springs',
		'Ojibways of Hiawatha First Nat',
		'Ojibways of Walpole Island Fir',
		'Omemee',
		'Onaping Falls',
		'Oneida First Nation',
		'Opasatika',
		'Ophir',
		'Orangeville',
		'Orillia',
		'Orleans',
		'Oro',
		'Orono',
		'Orrville',
		'Osgoode',
		'Oshawa',
		'Ottawa',
		'Otterville',
		'Owen Sound',
		'Oxdrift',
		'Oxford Mills',
		'Paisley',
		'Pakenham',
		'Palgrave',
		'Palmer Rapids',
		'Palmerston',
		'Paquette Corner',
		'Parham',
		'Paris',
		'Parkhill',
		'Parry Sound',
		'Pass Lake',
		'Peawanuck',
		'Pefferlaw',
		'Pelee Island',
		'Pelham',
		'Pembroke',
		'Penetanguishene',
		'Perrault Falls',
		'Perth',
		'Petawawa',
		'Peterborough',
		'Petrolia',
		'Pickering',
		'Pickle Lake',
		'Picton',
		'Pikangikum First Nation',
		'Pineal Lake',
		'Plantagenet',
		'Plattsville',
		'Pleasant Park',
		'Plevna',
		'Point Grondine First Nation',
		'Point Pelee',
		'Pointe au Baril',
		'Port Burwell',
		'Port Carling',
		'Port Colborne',
		'Port Credit',
		'Port Cunnington',
		'Port Dover',
		'Port Elgin',
		'Port Franks',
		'Port Hope',
		'Port Lambton',
		'Port Loring',
		'Port McNicoll',
		'Port Perry',
		'Port Robinson',
		'Port Rowan',
		'Port Stanley',
		'Port Sydney',
		'Portland',
		'Powassan',
		'Prescott',
		'Preston',
		'Princeton',
		'Puce',
		'Queenston',
		'Queensville',
		'Rainy Lake First Nation',
		'Rainy River',
		'Raith',
		'Ramore',
		'Rayside-Balfour',
		'Red Lake',
		'Red Rock',
		'Redbridge',
		'Redditt',
		'Renfrew',
		'Restoule',
		'Richmond',
		'Richmond Hill',
		'Ridgetown',
		'Ridgeway',
		'Ripley',
		'Rockland',
		'Rockwood',
		'Rodney',
		'Rolphton',
		'Rondeau',
		'Roseneath',
		'Rosseau',
		'Russell',
		'Ruthven',
		'Sachigo First Nation Reserve 1',
		'Saint Clair Beach',
		'Salem',
		'Sandwich',
		'Sandy Cove Acres',
		'Sandy Lake',
		'Sandy Lake First Nation',
		'Sapawe',
		'Sarnia',
		'Sauble Beach',
		'Saugeen First Nation',
		'Sault Ste. Marie',
		'Savant Lake',
		'Scarborough',
		'Schomberg',
		'Schreiber',
		'Scotland',
		'Seaforth',
		'Searchmont',
		'Sebright',
		'Sebringville',
		'Seeleys Bay',
		'Selby',
		'Selkirk',
		'Serpent River First Nation',
		'Severn Bridge',
		'Shakespeare',
		'Shannonville',
		'Sharbot Lake',
		'Shawanaga First Nation',
		'Shebandowan',
		'Shedden',
		'Shelburne',
		'Silver Water',
		'Simcoe',
		'Sioux Lookout',
		'Sioux Narrows',
		'Six Nations of the Grand River',
		'Smiths Falls',
		'Smithville',
		'Smooth Rock Falls',
		'Snelgrove',
		'Sombra',
		'South Mountain',
		'South River',
		'Southampton',
		'Spanish',
		'Sparta',
		'Spencerville',
		'Sprucedale',
		'St-Eugene',
		'St. Catharines',
		'St. Charles',
		'St. Clements',
		'St. Davids',
		'St. George',
		'St. Isidore de Prescott',
		'St. Jacobs',
		'St. Marys',
		'St. Regis',
		'St. Thomas',
		'Stayner',
		'Stevensville',
		'Stewarttown',
		'Stirling',
		'Stoke\'s Bay',
		'Stoney Creek',
		'Stoney Point',
		'Stouffville',
		'Straffordville',
		'Stratford',
		'Strathroy',
		'Stratton',
		'Streetsville',
		'Stroud',
		'Sturgeon Falls',
		'Sudbury',
		'Sultan',
		'Summer Beaver',
		'Sunderland',
		'Sundridge',
		'Sutton',
		'Swastika',
		'Sydenham',
		'Tamworth',
		'Tara',
		'Tavistock',
		'Taylor Corners',
		'Tecumseh',
		'Teeswater',
		'Temagami',
		'Terrace Bay',
		'Thamesford',
		'Thamesville',
		'The Eabametoong (Fort Hope) Fi',
		'Thedford',
		'Thessalon',
		'Thessalon First Nation',
		'Thornbury',
		'Thorndale',
		'Thorne',
		'Thornhill',
		'Thorold',
		'Thunder Bay',
		'Thurlow',
		'Tilbury',
		'Tillsonburg',
		'Timmins',
		'Tiverton',
		'Tobermory',
		'Toledo',
		'Toronto',
		'Toronto Island',
		'Tottenham',
		'Trenton',
		'Trout Creek',
		'Trowbridge',
		'Tweed',
		'Udora',
		'Uniondale',
		'Unionville',
		'Upsala',
		'Utterson',
		'Uxbridge',
		'Valley East',
		'Vanier',
		'Vankleek Hill',
		'Vaughan',
		'Vermilion Bay',
		'Verner',
		'Verona',
		'Victoria',
		'Vineland',
		'Virginiatown',
		'Wabigoon',
		'Wainfleet',
		'Walden',
		'Walkerton',
		'Wallaceburg',
		'Wapekeka First Nation',
		'Wardsville',
		'Warkworth',
		'Warren',
		'Wasaga Beach',
		'Waterdown',
		'Waterford',
		'Waterloo',
		'Watford',
		'Waubaushene',
		'Wawa',
		'Webbwood',
		'Webequie',
		'Welcome',
		'Welland',
		'Wellandport',
		'Wellesley',
		'Wellington',
		'West Guilford',
		'West Lincoln',
		'West Lorne',
		'Westmeath',
		'Westport',
		'Westree',
		'Wheatley',
		'Whitby',
		'Whitchurch-Stouffville',
		'White River',
		'Whitefish',
		'Whitefish Falls',
		'Whitefish River First Nation',
		'Whitney',
		'Wiarton',
		'Wikwemikong',
		'Wilberforce',
		'Williamsburg',
		'Winchester',
		'Windermere',
		'Windsor',
		'Wingham',
		'Winona',
		'Woodbridge',
		'Woodstock',
		'Woodville',
		'Wooler',
		'Wunnummin Lake',
		'Wyoming',
		'Yarker',
		'York',
		'Zurich'
	),
	// Prince Edward Island
	'PE' => array(
		'Alberton',
		'Bedeque',
		'Borden',
		'Cardigan',
		'Charlottetown',
		'Cornwall',
		'Covehead',
		'Crapaud',
		'East Point',
		'Eldon',
		'Georgetown',
		'Hunter River',
		'Kensington',
		'Montague',
		'Morell',
		'Mount Stewart',
		'Murray River',
		'New Haven',
		'New London',
		'O\'Leary',
		'Rusticoville',
		'Souris',
		'South Lake',
		'St. Peters',
		'Stratford',
		'Summerside',
		'Tignish',
		'Tyne Valley',
		'Vernon River',
		'Wellington'
	),
	// Quebec
	'QC' => array(
		'Abercorn',
		'Acton Vale',
		'Adamsville',
		'Aguanish',
		'Albanel',
		'Alma',
		'Alouette',
		'Amos',
		'Amqui',
		'Angliers',
		'Anjou',
		'Anse-Saint-Jean',
		'Armagh',
		'Arundel',
		'Asbestos',
		'Ascot',
		'Ascot Corner',
		'Ashuapmushuan',
		'Aston-Jonction',
		'Ayer\'s Cliff',
		'Aylmer',
		'Bagotville',
		'Baie-Comeau',
		'Baie-de-Shawinigan',
		'Baie-des-Sables',
		'Baie-du-Febvre',
		'Baie-d\'Urfe',
		'Baie-Johan-Beetz',
		'Baie-Sainte-Catherine',
		'Baie-St-Paul',
		'Baie-Trinite',
		'Barachois',
		'Barkmere',
		'Barraute',
		'Batiscan',
		'Beaconsfield',
		'Beaucanton',
		'Beauceville',
		'Beauharnois',
		'Beaulac-Garthby',
		'Beaumont',
		'Beauport',
		'Beaupre',
		'Becancour',
		'Bedford',
		'Belle Neige',
		'Bellefeuille',
		'Belleterre',
		'Beloeil',
		'Bergeronnes',
		'Berthierville',
		'Betsiamites',
		'Biencourt',
		'Bishopton',
		'Black Lake',
		'Blainville',
		'Blanc-Sablon',
		'Bois-des-Filion',
		'Boisbriand',
		'Boischatel',
		'Bonaventure',
		'Bonne-Esperance',
		'Boucherville',
		'Bouchette',
		'Breakeyville',
		'Brigham',
		'Brome',
		'Bromont',
		'Bromptonville',
		'Brossard',
		'Brownsburg',
		'Bryson',
		'Buckingham',
		'Bury',
		'Cabano',
		'Cacouna',
		'Cadillac',
		'Calumet',
		'Campbell\'s Bay',
		'Candiac',
		'Cantley',
		'Cap-a-l\'Aigle',
		'Cap-aux-Meules',
		'Cap-Chat',
		'Cap-de-la-Madeleine',
		'Cap-des-Rosiers',
		'Cap-Rouge',
		'Cap-Saint-Ignace',
		'Caplan',
		'Carignan',
		'Carillon',
		'Carleton',
		'Causapscal',
		'Chambly',
		'Chambord',
		'Champlain',
		'Chandler',
		'Chapais',
		'Chapeau',
		'Charette',
		'Charlemagne',
		'Charlesbourg',
		'Charlevoix',
		'Charny',
		'Chartierville',
		'Chateau-Richer',
		'Chateauguay',
		'Chelsea',
		'Cheneville',
		'Chesterville',
		'Chevery',
		'Chibougamau',
		'Chicoutimi',
		'Chisasibi',
		'Chomedey',
		'Chute-aux-Outardes',
		'Chute-des-Passes',
		'Clericy',
		'Clermont',
		'Cloridorme',
		'Clova',
		'Coaticook',
		'Colombier',
		'Compton',
		'Contrecoeur',
		'Cookshire',
		'Cote-St-Luc',
		'Coteau-du-Lac',
		'Courcelette',
		'Courcelles',
		'Cowansville',
		'Crabtree',
		'Danville',
		'Daveluyville',
		'Deauville',
		'Degelis',
		'Delisle',
		'Delson',
		'Desbiens',
		'Deschaillons-sur-Saint-Laurent',
		'Deux-Montagnes',
		'Disraeli',
		'Dolbeau-Mistassini',
		'Dollard-des-Ormeaux',
		'Donnacona',
		'Dorval',
		'Drummondville',
		'Dubuisson',
		'Dunham',
		'Duparquet',
		'Dupuy',
		'Duvernay',
		'East Angus',
		'East Broughton',
		'East Farnham',
		'East Hereford',
		'Eastmain',
		'Eastman',
		'Entrelacs',
		'Esterel',
		'Evain',
		'Fabre',
		'Fabreville',
		'Falardeau',
		'Farnham',
		'Fassett',
		'Ferland',
		'Ferme-Neuve',
		'Fermont',
		'Fleurimont',
		'Forestville',
		'Fort-Coulonge',
		'Fortierville',
		'Fossambault-sur-le-Lac',
		'Frampton',
		'Franklin Centre',
		'Frelighsburg',
		'Fugereville',
		'Gaspe',
		'Gatineau',
		'Gentilly',
		'Girardville',
		'Godbout',
		'Gracefield',
		'Granby',
		'Grand-Mere',
		'Grand-Remous',
		'Grande-Entree',
		'Grande-Riviere',
		'Grande-Vallee',
		'Grandes-Bergeronnes',
		'Grandes-Piles',
		'Greenfield Park',
		'Grenville',
		'Guigues',
		'Ham-Nord',
		'Hammond',
		'Hampstead',
		'Harrington Harbour',
		'Havre-Aubert',
		'Havre-aux-Maisons',
		'Havre-St-Pierre',
		'Hebertville',
		'Hebertville-Station',
		'Hemmingford',
		'Henryville',
		'Howick',
		'Hudson',
		'Hull',
		'Huntingdon',
		'Iberville',
		'Ile-aux-Coudres',
		'Iles-de-la-Madeleine',
		'Inukjuak',
		'Inverness',
		'Joliette',
		'Jonquiere',
		'Joutel',
		'Kangiqsualujjuaq',
		'Kangirsuk',
		'Kateville',
		'Kazabazua',
		'Kingsbury',
		'Kingsey Falls',
		'Kirkland',
		'Knowlton',
		'Kuujjuaq',
		'La Baie',
		'La Corne',
		'La Dore',
		'La Grande',
		'La Guadeloupe',
		'La Malbaie',
		'La Martre',
		'La Minerve',
		'La Patrie',
		'La Plaine',
		'La Pocatiere',
		'La Prairie',
		'La Reine',
		'La Romaine',
		'La Sarre',
		'La Tuque',
		'Labelle',
		'Lac Kenogami',
		'Lac-au-Saumon',
		'Lac-aux-Sables',
		'Lac-Bouchette',
		'Lac-Brome',
		'Lac-Delage',
		'Lac-des-Ecorces',
		'Lac-Drolet',
		'Lac-du-Cerf',
		'Lac-Edouard',
		'Lac-Etchemin',
		'Lac-Frontiere',
		'Lac-Poulin',
		'Lac-Saguay',
		'Lac-Sergent',
		'Lac-St-Joseph',
		'Lachenaie',
		'Lachine',
		'Lachute',
		'Lacolle',
		'Lafontaine',
		'Lake Megantic',
		'Lambton',
		'Lanoraie',
		'LaSalle',
		'Laterriere',
		'Latulipe',
		'Laurentides',
		'Laurier-Station',
		'Laurierville',
		'Laval',
		'Laval des Rapides',
		'Laval Ouest',
		'Lavaltrie',
		'Laverlochere',
		'Lawrenceville',
		'Le Bic',
		'Le Gardeur',
		'Lebel-sur-Quevillon',
		'Leclercville',
		'LeMoyne',
		'Lennoxville',
		'Lery',
		'Les Boules',
		'Les Cedres',
		'Les Coteaux',
		'Les Eboulements',
		'Les Escoumins',
		'Les Mechins',
		'Levis',
		'Longueuil',
		'Loretteville',
		'Lorraine',
		'Lorrainville',
		'Louiseville',
		'Lourdes de Blanc Sablon',
		'Louvicourt',
		'Low',
		'Luceville',
		'Luskville',
		'Lyster',
		'L\'Acadie',
		'L\'Ancienne-Lorette',
		'L\'Ange-Gardien',
		'L\'Annonciation',
		'L\'Assomption',
		'L\'Avenir',
		'L\'Epiphanie',
		'L\'Ile-Aux-Noix',
		'L\'Ile-Bizard',
		'L\'Ile-Cadieux',
		'L\'Ile-Dorval',
		'L\'Ile-d\'Entree',
		'L\'Ile-Perrot',
		'L\'Île-Verte',
		'L\'Islet',
		'Macamic',
		'Magog',
		'Malartic',
		'Manic-Cinq',
		'Maniwaki',
		'Manouane',
		'Manseau',
		'Mansonville',
		'Maple Grove',
		'Maria',
		'Marieville',
		'Marsoui',
		'Mascouche',
		'Maskinonge',
		'Masson-Angers',
		'Massueville',
		'Mastigouche',
		'Matagami',
		'Matane',
		'Matapedia',
		'Mcmasterville',
		'Melbourne',
		'Mellin',
		'Melocheville',
		'Mercier',
		'Metabetchouan',
		'Metis-sur-Mer',
		'Mirabel',
		'Mistassini',
		'Moisie',
		'Mont Bechervaise',
		'Mont St Grégoire',
		'Mont-Joli',
		'Mont-Laurier',
		'Mont-Louis',
		'Mont-Rolland',
		'Mont-Royal',
		'Mont-St-Hilaire',
		'Mont-St-Pierre',
		'Mont-Tremblant',
		'Montebello',
		'Montmagny',
		'Montreal',
		'Montreal - Est',
		'Montréal - Nord',
		'Montréal - Ouest',
		'Morin-Heights',
		'Murdochville',
		'Mutton Bay',
		'Nantes',
		'Napierville',
		'Natashquan',
		'Nedelec',
		'Neuville',
		'New Carlisle',
		'New Glasgow',
		'New Richmond',
		'Newport',
		'Nicolet',
		'Norbertville',
		'Normandin',
		'Normetal',
		'North Hatley',
		'Notre Dame de Bonsecours',
		'Notre Dame de Lourdes',
		'Notre Dame De L\'Ile Perrot',
		'Notre Dame des Laurentides',
		'Notre Dame Des Prairies',
		'Notre Dame Du Portage',
		'Notre-Dame-de-la-Paix',
		'Notre-Dame-de-la-Salette',
		'Notre-Dame-de-Stanbridge',
		'Notre-Dame-du-Bon-Conseil',
		'Notre-Dame-du-Lac',
		'Notre-Dame-du-Laus',
		'Notre-Dame-du-Nord',
		'Nouvelle',
		'Oka',
		'Omerville',
		'Orford',
		'Ormstown',
		'Otterburn Park',
		'Outremont',
		'Palmarolle',
		'Papineauville',
		'Parent',
		'Perce',
		'Peribonka',
		'Perkins',
		'Petite-Riviere-St-Francois',
		'Philipsburg',
		'Pierrefonds',
		'Pierreville',
		'Pincourt',
		'Pintendre',
		'Plaisance',
		'Plessisville',
		'Pohenegamook',
		'Pointe Aux Trembles',
		'Pointe-a-la-Croix',
		'Pointe-au-Pere',
		'Pointe-aux-Outardes',
		'Pointe-Calumet',
		'Pointe-Claire',
		'Pointe-des-Cascades',
		'Pointe-des-Monts',
		'Pointe-Fortune',
		'Pointe-Lebel',
		'Pont-Rouge',
		'Pont-Viau',
		'Pontiac',
		'Port-Cartier',
		'Port-Daniel',
		'Port-Menier',
		'Portage-du-Fort',
		'Portneuf',
		'Poste-de-la-Baleine',
		'Prevost',
		'Price',
		'Princeville',
		'Puvirnituq',
		'Quebec',
		'Quyon',
		'Radisson',
		'Rawdon',
		'Remigny',
		'Repentigny',
		'Réserve faunique de Rimouski',
		'Réserve faunique la Vérendrye',
		'Réserves fauniques de Matane e',
		'Richelieu',
		'Richmond',
		'Rigaud',
		'Rimouski',
		'Rimouski-Est',
		'Ripon',
		'Riviere-a-Pierre',
		'Riviere-au-Renard',
		'Riviere-au-Tonnerre',
		'Riviere-Beaudette',
		'Riviere-Bleue',
		'Riviere-du-Loup',
		'Riviere-Heva',
		'Riviere-St-Jean',
		'Robertsonville',
		'Roberval',
		'Rochebaucourt',
		'Rock Forest',
		'Rollet',
		'Rosemere',
		'Rougemont',
		'Rouyn-Noranda',
		'Roxboro',
		'Roxton Falls',
		'Roxton Pond',
		'Sabrevois',
		'Sacre Coeur',
		'Saint Alexandre D\'Iberville',
		'Saint Alphonse de Granby',
		'Saint Amable',
		'Saint Antoine Des Laurentides',
		'Saint Antoine Sur Richelieu',
		'Saint Antonin',
		'Saint Athanase',
		'Saint Calixte',
		'Saint Charles Borromee',
		'Saint Charles Sur Richelieu',
		'Saint Christophe D\'Arthabaska',
		'Saint Colomban',
		'Saint Denis De Brompton',
		'Saint Denis Sur Richelieu',
		'Saint Esprit',
		'Saint Etienne de Beauharnois',
		'Saint Etienne de Lauzon',
		'Saint Gerard Majella',
		'Saint Isidore de la Prairie',
		'Saint Jean Baptiste',
		'Saint Jean D\'Orleans',
		'Saint Joachim',
		'Saint Joseph De La Pointe De L',
		'Saint Laurent D\'Orleans',
		'Saint Lazare De Vaudreuil',
		'Saint Lin Laurentides',
		'Saint Marc Sur Richelieu',
		'Saint Mathias Sur Richelieu',
		'Saint Mathieu de Beloeil',
		'Saint Mathieu de la Prairie',
		'Saint Maurice',
		'Saint Norbert D\'Arthabaska',
		'Saint Paul D\'Industrie',
		'Saint Philippe',
		'Saint Pierre D\'Orleans',
		'Saint Robert',
		'Saint Roch De L\'Achigan',
		'Saint Roch De Richelieu',
		'Saint Sulpice',
		'Saint Thomas',
		'Saint Urbain Premier',
		'Saint Valere',
		'Saint Victoire de Sorel',
		'Saint-Alexis-de-Montcalm',
		'Saint-Côme',
		'Saint-Donat',
		'Saint-Élie',
		'Saint-Élie-d\'Orford',
		'Saint-Ferdinand',
		'Saint-Ferréol-les-neiges',
		'Saint-Hubert',
		'Saint-Hyacinthe',
		'Saint-Michel-des-Saints',
		'Sainte Angele De Monnoir',
		'Sainte Ann De Sorel',
		'Sainte Brigide D\'Iberville',
		'Sainte Cecile De Milton',
		'Sainte Dorotheé',
		'Sainte Famille',
		'Sainte Marie Salome',
		'Sainte Marthe Du Cap',
		'Sainte Sophie',
		'Sainte Therese De Blainville',
		'Salaberry-de-Valleyfield',
		'Salluit',
		'Sanmaur',
		'Sault-au-Mouton',
		'Sawyerville',
		'Sayabec',
		'Schefferville',
		'Scotstown',
		'Senneterre',
		'Senneville',
		'Sept-Iles',
		'Shawbridge',
		'Shawinigan',
		'Shawinigan-Sud',
		'Shawville',
		'Shefford',
		'Sherbrooke',
		'Shigawake',
		'Shipshaw',
		'Sillery',
		'Sorel-Tracy',
		'Squatec',
		'St-Adelphe',
		'St-Adolphe-de-Dudswell',
		'St-Adolphe-d\'Howard',
		'St-Agapit',
		'St-Aime',
		'St-Albert',
		'St-Alexandre-de-Kamouraska',
		'St-Alexis-de-Matapedia',
		'St-Alexis-des-Monts',
		'St-Alphonse-Rodriguez',
		'St-Andre',
		'St-Andre-Avellin',
		'St-Andre-du-Lac-St-Jean',
		'St-Andre-Est',
		'St-Anselme',
		'St-Antoine',
		'St-Antoine-de-Tilly',
		'St-Apollinaire',
		'St-Augustin-de-Desmaures',
		'St-Barnabe',
		'St-Barthelemy',
		'St-Basile-le-Grand',
		'St-Basile-Sud',
		'St-Blaise-sur-Richelieu',
		'St-Boniface-de-Shawinigan',
		'St-Bruno',
		'St-Bruno-de-Montarville',
		'St-Calixte-de-Kilkenny',
		'St-Casimir',
		'St-Celestin',
		'St-Cesaire',
		'St-Charles-de-Bellechasse',
		'St-Chrysostome',
		'St-Clet',
		'St-Constant',
		'St-Cyrille-de-Wendover',
		'St-Damase',
		'St-Damien-de-Buckland',
		'St-Denis',
		'St-Edouard-de-Lotbiniere',
		'St-Eleuthere',
		'St-Emile',
		'St-Emile-de-Suffolk',
		'St-Ephrem-de-Beauce',
		'St-Ephrem-de-Tring',
		'St-Eugene-de-Guigues',
		'St-Eustache',
		'St-Fabien-de-Panet',
		'St-Felicien',
		'St-Felix-de-Kingsey',
		'St-Felix-de-Valois',
		'St-Fidele-de-Mont-Murray',
		'St-Flavien',
		'St-Francois-du-Lac',
		'St-Fulgence',
		'St-Gabriel',
		'St-Gabriel-de-Brandon',
		'St-Gedeon',
		'St-Georges',
		'St-Georges-de-Beauce',
		'St-Georges-de-Cacouna',
		'St-Gerard',
		'St-Germain-de-Grantham',
		'St-Gregoire-de-Greenlay',
		'St-Guillaume',
		'St-Hilarion',
		'St-Hippolyte',
		'St-Honore-de-Beauce',
		'St-Honore-de-Chicoutimi',
		'St-Hugues',
		'St-Irenee',
		'St-Jacques',
		'St-Jean-Chrysostome',
		'St-Jean-de-Dieu',
		'St-Jean-de-Matha',
		'St-Jean-Port-Joli',
		'St-Jean-sur-Richelieu',
		'St-Jerome',
		'St-Joseph-de-Beauce',
		'St-Joseph-de-la-Rive',
		'St-Joseph-de-Sorel',
		'St-Jovite',
		'St-Jude',
		'St-Just-de-Bretenieres',
		'St-Lambert',
		'St-Lambert-de-Lauzon',
		'St-Laurent',
		'St-Leon-le-Grand',
		'St-Leonard',
		'St-Leonard-d\'Aston',
		'St-Liboire',
		'St-Lin',
		'St-Louis-de-France',
		'St-Luc',
		'St-Ludger',
		'St-Magloire',
		'St-Malachie',
		'St-Malo',
		'St-Marc-des-Carrieres',
		'St-Methode-de-Frontenac',
		'St-Michel-de-Bellechasse',
		'St-Moose',
		'St-Nazaire-d\'Acton',
		'St-Nicolas',
		'St-Noel',
		'St-Odilon-de-Cranbourne',
		'St-Ours',
		'St-Pacome',
		'St-Pamphile',
		'St-Pascal',
		'St-Patrice-de-Beaurivage',
		'St-Paul-de-Montminy',
		'St-Paul-d\'Abbotsford',
		'St-Paulin',
		'St-Philippe-de-Neri',
		'St-Pie',
		'St-Pie-de-Guire',
		'St-Pierre',
		'St-Pierre-de-Wakefield',
		'St-Pierre-les-Becquets',
		'St-Polycarpe',
		'St-Prime',
		'St-Prosper-de-Dorchester',
		'St-Raymond',
		'St-Redempteur',
		'St-Remi',
		'St-Rene-de-Matane',
		'St-Roch-de-Mekinac',
		'St-Roch-des-Aulnaies',
		'St-Romuald',
		'St-Sauveur',
		'St-Sauveur-des-Monts',
		'St-Simeon',
		'St-Simon-de-Bagot',
		'St-Simon-de-Rimouski',
		'St-Sylvere',
		'St-Sylvestre',
		'St-Theophile',
		'St-Thomas-d\'Aquin',
		'St-Timothee',
		'St-Tite',
		'St-Tite-des-Caps',
		'St-Ubalde',
		'St-Ulric',
		'St-Urbain',
		'St-Victor',
		'St-Wenceslas',
		'St-Zacharie',
		'St-Zenon',
		'St-Zephirin',
		'St-Zotique',
		'St. Ambroise de Chicoutimi',
		'St. Basile de Portneuf',
		'St. Bernard de Dorchester',
		'St. Come de Kennebec',
		'St. Edouard de Frampton',
		'St. Fabien de Rimouski',
		'St. Ferdinand d\'Halifax',
		'St. Fidele',
		'St. Gabriel de Rimouski',
		'St. Gedeon de Beauce',
		'St. Gregoire de Nicolet',
		'St. Henri de Levis',
		'St. Honore',
		'St. Leon De Chic.',
		'St. Martin de Beauce',
		'St. Moise',
		'St. Raphael de Bellechasse',
		'St. Sebastien',
		'St. Stanislas de Champlain',
		'St. Theodore de Chertsey',
		'St. Victor de Beauce',
		'St. Vincent de Paul',
		'Stanstead',
		'Ste-Adele',
		'Ste-Agathe',
		'Ste-Agathe-des-Monts',
		'Ste-Agathe-Sud',
		'Ste-Anne-de-Beaupre',
		'Ste-Anne-de-Bellevue',
		'Ste-Anne-de-la-Perade',
		'Ste-Anne-de-Portneuf',
		'Ste-Anne-des-Monts',
		'Ste-Anne-des-Plaines',
		'Ste-Anne-du-Lac',
		'Ste-Blandine',
		'Ste-Brigitte-de-Laval',
		'Ste-Catherine',
		'Ste-Clotilde-de-Horton',
		'Ste-Eulalie',
		'Ste-Felicite',
		'Ste-Foy',
		'Ste-Genevieve',
		'Ste-Helene-de-Bagot',
		'Ste-Henedine',
		'Ste-Jeanne-d\'Arc',
		'Ste-Julie',
		'Ste-Julie-de-Vercheres',
		'Ste-Julienne',
		'Ste-Justine',
		'Ste-Lucie-de-Beauregard',
		'Ste-Madeleine',
		'Ste-Marguerite',
		'Ste-Marie-de-Beauce',
		'Ste-Marie-de-Blandford',
		'Ste-Marthe',
		'Ste-Marthe-sur-le-Lac',
		'Ste-Perpetue',
		'Ste-Petronille',
		'Ste-Rosalie',
		'Ste-Rose',
		'Ste-Rose-de-Watford',
		'Ste-Rose-du-Nord',
		'Ste-Sophie-de-Levrard',
		'Ste-Thecle',
		'Ste-Therese',
		'Ste-Veronique',
		'Ste-Victoire',
		'Ste. Agathe de Lotbiniere',
		'Ste. Angele de Laval',
		'Ste. Cecile Masham',
		'Ste. Claire de Dorchester',
		'Ste. Croix de Lotbiniere',
		'Ste. Gertrude',
		'Ste. Justine de Newton',
		'Ste. Martine',
		'Ste. Methode de Frontenac',
		'Ste. Monique de Nicolet',
		'Stoke',
		'Stoneham',
		'Stratford',
		'Stukely-Sud',
		'Sutton',
		'Tadoussac',
		'Taschereau',
		'Tasiujaq',
		'Temiscaming',
		'Terrasse Vaudreuil',
		'Terrebonne',
		'Tete-a-la-Baleine',
		'Thetford Mines',
		'Thurso',
		'Tingwick',
		'Tremblay',
		'Tring-Jonction',
		'Trois-Pistoles',
		'Trois-Rivieres',
		'Umiujaq',
		'Upton',
		'Val-Alain',
		'Val-Barrette',
		'Val-Belair',
		'Val-Brillant',
		'Val-David',
		'Val-des-Bois',
		'Val-d\'Or',
		'Valcartier',
		'Valcourt',
		'Vallee-Jonction',
		'Vanier',
		'Varennes',
		'Vaudreuil',
		'Vaudreuil Dorion',
		'Vaudreuil-sur-le-Lac',
		'Venise-en-Quebec',
		'Vercheres',
		'Verdun',
		'Victoriaville',
		'Ville-Marie',
		'Vimont',
		'Wakefield',
		'Warden',
		'Warwick',
		'Waskaganish',
		'Waswanipi',
		'Waterloo',
		'Waterville',
		'Weedon',
		'Weedon Centre',
		'Wemindji',
		'Wendover',
		'West Brome',
		'Westbury',
		'Westmount',
		'Wickham',
		'Windsor',
		'Woburn',
		'Wotton',
		'Yamachiche',
		'Yamaska',
		'Yamaska-Est'
	),
	// Saskatchewan
	'SK' => array(
		'Abbey',
		'Aberdeen',
		'Abernethy',
		'Alameda',
		'Alida',
		'Allan',
		'Alsask',
		'Alvena',
		'Aneroid',
		'Arborfield',
		'Archerwill',
		'Arcola',
		'Asquith',
		'Assiniboia',
		'Avonlea',
		'Balcarres',
		'Balgonie',
		'Battleford',
		'Beauval',
		'Beechy',
		'Bengough',
		'Bethune',
		'Bienfait',
		'Big River',
		'Biggar',
		'Birch Hills',
		'Birsay',
		'Blaine Lake',
		'Borden',
		'Bredenbury',
		'Briercrest',
		'Broadview',
		'Brock',
		'Bruno',
		'Buchanan',
		'Buffalo Narrows',
		'Burstall',
		'Cabri',
		'Cadillac',
		'Calder',
		'Canoe Narrows',
		'Canora',
		'Canwood',
		'Carievale',
		'Carlyle',
		'Carnduff',
		'Caron',
		'Carrot River',
		'Central Butte',
		'Ceylon',
		'Chaplin',
		'Choiceland',
		'Christopher Lake',
		'Churchbridge',
		'Clavet',
		'Climax',
		'Cochin',
		'Coderre',
		'Coleville',
		'Colonsay',
		'Conquest',
		'Consul',
		'Coronach',
		'Craik',
		'Creelman',
		'Creighton',
		'Cudworth',
		'Cumberland House',
		'Cupar',
		'Cut Knife',
		'Dalmeny',
		'Davidson',
		'Debden',
		'Delisle',
		'Denzil',
		'Dillon',
		'Dinsmore',
		'Dodsland',
		'Domremy',
		'Drake',
		'Dubuc',
		'Duck Lake',
		'Dundurn',
		'Dysart',
		'Earl Grey',
		'Eastend',
		'Eatonia',
		'Edam',
		'Elbow',
		'Elfros',
		'Elrose',
		'Esterhazy',
		'Estevan',
		'Eston',
		'Eyebrow',
		'Fillmore',
		'Fleming',
		'Foam Lake',
		'Fond-du-Lac',
		'Fort Qu\'Appelle',
		'Fox Valley',
		'Francis',
		'Frobisher',
		'Frontier',
		'Gainsborough',
		'Glaslyn',
		'Glen Ewen',
		'Glenavon',
		'Goodeve',
		'Goodsoil',
		'Govan',
		'Gravelbourg',
		'Grayson',
		'Green Lake',
		'Grenfell',
		'Gull Lake',
		'Hafford',
		'Hague',
		'Hanley',
		'Harris',
		'Hawarden',
		'Hazlet',
		'Hepburn',
		'Herbert',
		'Herschel',
		'Hodgeville',
		'Holdfast',
		'Hudson Bay',
		'Humboldt',
		'Ile-a-la-Crosse',
		'Imperial',
		'Indian Head',
		'Invermay',
		'Ituna',
		'Jansen',
		'Kamsack',
		'Kelliher',
		'Kelvington',
		'Kenaston',
		'Kennedy',
		'Kenosee',
		'Kerrobert',
		'Key Lake',
		'Kincaid',
		'Kindersley',
		'Kinistino',
		'Kipling',
		'Kisbey',
		'Kyle',
		'La Loche',
		'La Ronge',
		'Lafleche',
		'Laird',
		'Lake Alma',
		'Lake Lenore',
		'Lampman',
		'Landis',
		'Lang',
		'Langenburg',
		'Langham',
		'Lanigan',
		'Lashburn',
		'Leader',
		'Leask',
		'Lemberg',
		'Leoville',
		'Leroy',
		'Lestock',
		'Liberty',
		'Limerick',
		'Lintlaw',
		'Lipton',
		'Lloydminster',
		'Loon Lake',
		'Loreburn',
		'Lucky Lake',
		'Lumsden',
		'Luseland',
		'Macklin',
		'Macrorie',
		'Maidstone',
		'Mankota',
		'Manor',
		'Maple Creek',
		'Marcelin',
		'Margo',
		'Marquis',
		'Marsden',
		'Marshall',
		'Martensville',
		'Maryfield',
		'Maymont',
		'Meacham',
		'Meadow Lake',
		'Meath Park',
		'Melfort',
		'Melville',
		'Meota',
		'Midale',
		'Middle Lake',
		'Milden',
		'Milestone',
		'Minton',
		'Mistatim',
		'Molanosa',
		'Montmartre',
		'Moose Jaw',
		'Moosomin',
		'Morse',
		'Mortlach',
		'Mossbank',
		'Naicam',
		'Neidpath',
		'Neilburg',
		'Neudorf',
		'Neville',
		'Nipawin',
		'Nokomis',
		'Norquay',
		'North Battleford',
		'North Portal',
		'Odessa',
		'Ogema',
		'Ormiston',
		'Osler',
		'Outlook',
		'Oxbow',
		'Paddockwood',
		'Pangman',
		'Paradise Hill',
		'Patuanak',
		'Paynton',
		'Pelican Narrows',
		'Pelly',
		'Pennant',
		'Pense',
		'Perdue',
		'Piapot',
		'Pierceland',
		'Pilot Butte',
		'Pinehouse',
		'Plato',
		'Plenty',
		'Ponteix',
		'Porcupine Plain',
		'Preeceville',
		'Prelate',
		'Prince Albert',
		'Prud\'homme',
		'Punnichy',
		'Quill Lake',
		'Qu\'Appelle',
		'Rabbit Lake',
		'Radisson',
		'Radville',
		'Raymore',
		'Redvers',
		'Regina',
		'Regina Beach',
		'Rhein',
		'Riceton',
		'Richmound',
		'Ridgedale',
		'Riverhurst',
		'Rocanville',
		'Rockglen',
		'Rose Valley',
		'Rosetown',
		'Rosthern',
		'Rouleau',
		'Saltcoats',
		'Sandy Bay',
		'Saskatoon',
		'Sceptre',
		'Scott',
		'Sedley',
		'Semans',
		'Shaunavon',
		'Sheho',
		'Shell Lake',
		'Shellbrook',
		'Simpson',
		'Sintaluta',
		'Smeaton',
		'Smiley',
		'Southend',
		'Southey',
		'Spalding',
		'Speers',
		'Spiritwood',
		'Springside',
		'Spy Hill',
		'St. Benedict',
		'St. Brieux',
		'St. Gregor',
		'St. Louis',
		'St. Walburg',
		'Stanley Mission',
		'Star City',
		'Stockholm',
		'Stony Rapids',
		'Storthoaks',
		'Stoughton',
		'Strasbourg',
		'Strongfield',
		'Sturgis',
		'Swift Current',
		'Tantallon',
		'Theodore',
		'Tisdale',
		'Togo',
		'Tompkins',
		'Torquay',
		'Tramping Lake',
		'Tribune',
		'Turnor Lake',
		'Turtleford',
		'Unity',
		'Uranium City',
		'Val Marie',
		'Vanguard',
		'Vanscoy',
		'Vibank',
		'Viscount',
		'Vonda',
		'Wadena',
		'Wakaw',
		'Waldheim',
		'Wapella',
		'Warman',
		'Waskesiu Lake',
		'Watrous',
		'Watson',
		'Wawota',
		'Webb',
		'Welwyn',
		'Weyburn',
		'White Fox',
		'Whitewood',
		'Wilcox',
		'Wilkie',
		'Willow Bunch',
		'Windthorst',
		'Wiseton',
		'Wishart',
		'Wollaston Lake',
		'Wolseley',
		'Wood Mountain',
		'Wynyard',
		'Yellow Creek',
		'Yellow Grass',
		'Yorkton',
		'Young',
		'Zealandia',
		'Zenon Park'
	),
	// Yukon
	'YT' => array(
		'Beaver Creek',
		'Burwash Landing',
		'Carcross',
		'Carmacks',
		'Dawson',
		'Destruction Bay',
		'Faro',
		'Haines Junction',
		'Marsh Lake',
		'Mayo',
		'Old Crow',
		'Pelly Crossing',
		'Ross River',
		'Swift River',
		'Tagish',
		'Teslin',
		'Watson Lake',
		'Whitehorse'
	)
);
