<?php
/**
 * Chinese Provinces (including Taiwan / Hong Kong / Macau)
 */
global $cities;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$cities['CN'] = array(
	'CN1' => array(
		'CN1A' => __( 'Beijing' ),
	),
	'CN2' => array(
		'CN2A' => __( 'Tianjin' ),

	),
	'CN3' => array(
		'CN3A' => __( 'Shijiazhuang' ),
		'CN3B' => __( 'Tangshan' ),
		'CN3C' => __( 'Qinhuangdao' ),
		'CN3D' => __( 'Handan' ),
		'CN3E' => __( 'Baoding' ),
		'CN3F' => __( 'Zhangjiakou' ),
		'CN3G' => __( 'Chende' ),
		'CN3H' => __( 'Cangzhou' ),
		'CN3I' => __( 'Langfang' ),
		'CN3J' => __( 'Hengshui' ),
	),
	'CN4' => array(
		'CN4A' => __( 'Taiyuan' ),
		'CN4B' => __( 'Datong' ),
		'CN4C' => __( 'Yangquan' ),
		'CN4D' => __( 'Changzhi' ),
		'CN4E' => __( 'Jincheng' ),
		'CN4F' => __( 'Suzhou' ),
		'CN4G' => __( 'Jinzhong' ),
		'CN4H' => __( 'Yunchen' ),
		'CN4I' => __( 'Xinzhou' ),
		'CN4J' => __( 'Linfen' ),
		'CN4K' => __( 'Luliang' ),
	),
	'CN5' => array(
		'CN5A' => __( 'Hohhot' ),
		'CN5B' => __( 'Baotou' ),
		'CN5C' => __( 'Wuhai' ),
		'CN5D' => __( 'Chifeng' ),
		'CN5E' => __( 'Tongliao' ),
		'CN5F' => __( 'Ordos' ),
		'CN5G' => __( 'Hulunbuir' ),
		'CN5H' => __( 'Bayannur' ),
		'CN5I' => __( 'Ulanqab' ),
		'CN5J' => __( 'Hinggan League' ),
		'CN5K' => __( 'Xilingol League' ),
		'CN5L' => __( 'Alxa League' ),
	),
	'CN6' => array(
		'CN6A' => __( 'Shenyang' ),
		'CN6B' => __( 'Dalian' ),
		'CN6C' => __( 'Anshan' ),
		'CN6D' => __( 'Fushun' ),
		'CN6E' => __( 'Benxi' ),
		'CN6F' => __( 'Dandong' ),
		'CN6G' => __( 'Jinzhou' ),
		'CN6H' => __( 'Yingkou' ),
		'CN6I' => __( 'Fuxin' ),
		'CN6J' => __( 'Liaoyang' ),
		'CN6K' => __( 'Panjin' ),
		'CN6L' => __( 'Tieling' ),
		'CN6M' => __( 'Chaoyang' ),
		'CN6N' => __( 'Huludao' ),
	),
	'CN7' => array(
		'CN7A' => __( 'Changchun' ),
		'CN7B' => __( 'Jilin' ),
		'CN7C' => __( 'Siping' ),
		'CN7D' => __( 'Liaoyuan' ),
		'CN7E' => __( 'Tonghua' ),
		'CN7F' => __( 'Baishan' ),
		'CN7G' => __( 'Songyuan' ),
		'CN7H' => __( 'Baicheng' ),
		'CN7I' => __( 'Yanbian Korean Autonomous Prefecture' ),
	),
	'CN8' => array(
		'CN8A' => __( 'Harbin' ),
		'CN8B' => __( 'Qiqihar' ),
		'CN8C' => __( 'Jixi' ),
		'CN8D' => __( 'Hegang' ),
		'CN8E' => __( 'Shuangyashan' ),
		'CN8F' => __( 'Daqing' ),
		'CN8G' => __( 'Yichun' ),
		'CN8H' => __( 'Jiamusi' ),
		'CN8I' => __( 'Qitaihe' ),
		'CN8J' => __( 'Mudanjiang' ),
		'CN8K' => __( 'Heihe' ),
		'CN8L' => __( 'Suihua' ),
		'CN8M' => __( "Daxing'anling Prefecture" ),
	),
	'CN9' => array(
		'CN9A' => __( 'Shanghai' ),

	),
	'CN10' => array(
		'CN10A' => __( 'Nanjing' ),
		'CN10B' => __( 'Wuxi' ),
		'CN10C' => __( 'Xuzhou' ),
		'CN10D' => __( 'Changzhou' ),
		'CN10E' => __( 'Suzhou' ),
		'CN10F' => __( 'Nantong' ),
		'CN10G' => __( 'Lianyungang' ),
		'CN10H' => __( 'Huaian' ),
		'CN10I' => __( 'Yancheng' ),
		'CN10J' => __( 'Yangzhou' ),
		'CN10K' => __( 'Zhenjiang' ),
		'CN10L' => __( 'Tayzhou' ),
		'CN10M' => __( 'Suqian' ),
	),
	'CN11' => array(
		'CN11A' => __( 'Hangzhou' ),
		'CN11B' => __( 'Ningbo' ),
		'CN11C' => __( 'Wenzhou' ),
		'CN11D' => __( 'Jiaxing' ),
		'CN11E' => __( 'Huzhou' ),
		'CN11F' => __( 'Shaoxing' ),
		'CN11G' => __( 'Jinhua' ),
		'CN11H' => __( 'Quzhou' ),
		'CN11I' => __( 'Zhoushan' ),
		'CN11J' => __( 'Taizhou' ),
		'CN11K' => __( 'Lishui' ),
	),
	'CN12' => array(
		'CN12A' => __( 'Hefei' ),
		'CN12B' => __( 'Wuhu' ),
		'CN12C' => __( 'Bengbu' ),
		'CN12D' => __( 'Huainan' ),
		'CN12E' => __( 'Maanshan' ),
		'CN12F' => __( 'Huaibei' ),
		'CN12G' => __( 'Tongling' ),
		'CN12H' => __( 'Anqing' ),
		'CN12I' => __( 'Huangshan' ),
		'CN12J' => __( 'Chuzhou' ),
		'CN12K' => __( 'Fuyang' ),
		'CN12L' => __( 'Swuzhou' ),
		'CN12M' => __( "Lu'an" ),
		'CN12N' => __( 'Bozhou' ),
		'CN12O' => __( 'Chizhou' ),
		'CN12P' => __( 'Xuancheng' ),
	),
	'CN13' => array(
		'CN13A' => __( 'Fuzhou' ),
		'CN13B' => __( 'Xiamen' ),
		'CN13C' => __( 'Putian' ),
		'CN13D' => __( 'Sanming' ),
		'CN13E' => __( 'Quanzhou' ),
		'CN13F' => __( 'Zhangzhou' ),
		'CN13G' => __( 'Nanping' ),
		'CN13H' => __( 'Longyan' ),
		'CN13I' => __( 'Ningde' ),
	),
	'CN14' => array(
		'CN14A' => __( 'Nanchang' ),
		'CN14B' => __( 'Jingdezhen' ),
		'CN14C' => __( 'Pingxiang' ),
		'CN14D' => __( 'Jiujiang' ),
		'CN14E' => __( 'Xinyu' ),
		'CN14F' => __( 'Yingtan' ),
		'CN14G' => __( 'Ganzhou' ),
		'CN14H' => __( "Ji'an" ),
		'CN14I' => __( 'Yichun' ),
		'CN14J' => __( 'Fuuzhou' ),
		'CN14K' => __( 'Shangrao' ),
	),
	'CN15' => array(
		'CN15A' => __( 'Jinan' ),
		'CN15B' => __( 'Qingdao' ),
		'CN15C' => __( 'Zibo' ),
		'CN15D' => __( 'Zaozhuang' ),
		'CN15E' => __( 'Dongying' ),
		'CN15F' => __( 'Yantai' ),
		'CN15G' => __( 'Weifang' ),
		'CN15H' => __( 'Jining' ),
		'CN15I' => __( 'Taian' ),
		'CN15J' => __( 'Weihai' ),
		'CN15K' => __( 'Rizhao' ),
		'CN15L' => __( 'Laiwu' ),
		'CN15M' => __( 'Linyi' ),
		'CN15N' => __( 'Dezhou' ),
		'CN15O' => __( 'Liaocheng' ),
		'CN15P' => __( 'Binzhou' ),
		'CN15Q' => __( 'Heze' ),
	),
	'CN16' => array(
		'CN16A' => __( 'Zhengzhou' ),
		'CN16B' => __( 'Kaifeng' ),
		'CN16C' => __( 'Luoyang' ),
		'CN16D' => __( 'Pingdingshan' ),
		'CN16E' => __( 'Anyang' ),
		'CN16F' => __( 'Hebi' ),
		'CN16G' => __( 'Xinxiang' ),
		'CN16H' => __( 'Jiaozuo' ),
		'CN16I' => __( 'Jiyuan' ),
		'CN16J' => __( 'Puyang' ),
		'CN16K' => __( 'Xuchang' ),
		'CN16L' => __( 'Luohe' ),
		'CN16M' => __( 'Sanmenxia' ),
		'CN16N' => __( 'Nanyang' ),
		'CN16O' => __( 'Shangqiu' ),
		'CN16P' => __( 'Xinyang' ),
		'CN16Q' => __( 'Zhoukou' ),
		'CN16R' => __( 'Zhumadian' ),
	),
	'CN17' => array(
		'CN17A' => __( 'Wuhan' ),
		'CN17B' => __( 'Huangshi' ),
		'CN17C' => __( 'Shiyan' ),
		'CN17D' => __( 'Yichang' ),
		'CN17E' => __( 'Xiangyang' ),
		'CN17F' => __( 'Ezhou' ),
		'CN17G' => __( 'Jingmen' ),
		'CN17H' => __( 'Xiaogan' ),
		'CN17I' => __( 'Jingzhou' ),
		'CN17J' => __( 'Huanggang' ),
		'CN17K' => __( 'Xianning' ),
		'CN17L' => __( 'Suizhou' ),
		'CN17M' => __( 'Enshi Tujia and Miao Autonomous Prefecture' ),
		'CN17N' => __( 'Xiantao' ),
		'CN17O' => __( 'Qianjiang' ),
		'CN17P' => __( 'Tianmen' ),
		'CN17Q' => __( 'Shennongjia' ),
	),
	'CN18' => array(
		'CN18A' => __( 'Changsha' ),
		'CN18B' => __( 'Zhuzhou' ),
		'CN18C' => __( 'Xiangtan' ),
		'CN18D' => __( 'Hengyang' ),
		'CN18E' => __( 'Shaoyang' ),
		'CN18F' => __( 'Yueyang' ),
		'CN18G' => __( 'Changde' ),
		'CN18H' => __( 'Zhangjiajie' ),
		'CN18I' => __( 'Yiyang' ),
		'CN18J' => __( 'Chenzhou' ),
		'CN18K' => __( 'Yongzhou' ),
		'CN18L' => __( 'Huaihua' ),
		'CN18M' => __( 'Loudi' ),
		'CN18N' => __( 'Xiangxi Tujia and Miao Autonomous Prefecture' ),
	),
	'CN19' => array(
		'CN19A' => __( 'Guangzhou' ),
		'CN19B' => __( 'Shaoguan' ),
		'CN19C' => __( 'Shenzhen' ),
		'CN19D' => __( 'Zhuhai' ),
		'CN19E' => __( 'Shantou' ),
		'CN19F' => __( 'Foshan' ),
		'CN19G' => __( 'Jiangmen' ),
		'CN19H' => __( 'Zhanjiang' ),
		'CN19I' => __( 'Maoming' ),
		'CN19J' => __( 'Zhaoqing' ),
		'CN19K' => __( 'Huizhou' ),
		'CN19L' => __( 'Meizhou' ),
		'CN19M' => __( 'Shanwei' ),
		'CN19N' => __( 'Heyuan' ),
		'CN19O' => __( 'Yangjiang' ),
		'CN19P' => __( 'Qingyuan' ),
		'CN19Q' => __( 'Dongguan' ),
		'CN19R' => __( 'Zhongshan' ),
		'CN19S' => __( 'Pratas Islands' ),
		'CN19T' => __( 'Chaozhou' ),
		'CN19U' => __( 'Jieyang' ),
		'CN19V' => __( 'Yunfu' ),
	),
	'CN20' => array(
		'CN20A' => __( 'Nanning' ),
		'CN20B' => __( 'Liuzhou' ),
		'CN20C' => __( 'Guilin' ),
		'CN20D' => __( 'Wuzhou' ),
		'CN20E' => __( 'Beihai' ),
		'CN20F' => __( 'Fangchenggang' ),
		'CN20G' => __( 'Qinzhou' ),
		'CN20H' => __( 'Guigang' ),
		'CN20I' => __( 'Yulin' ),
		'CN20J' => __( 'Baise' ),
		'CN20K' => __( 'Hezhou' ),
		'CN20L' => __( 'Hechi' ),
		'CN20M' => __( 'Laibin' ),
		'CN20N' => __( 'Chongzuo' ),
	),
	'CN21' => array(
		'CN21A' => __( 'Haikou' ),
		'CN21B' => __( 'Sanya' ),
		'CN21C' => __( 'Sansha' ),
		'CN21D' => __( 'Wuzhishan' ),
		'CN21E' => __( 'Qionghai' ),
		'CN21F' => __( 'Danzhou' ),
		'CN21G' => __( 'Wenchang' ),
		'CN21H' => __( 'Wanning' ),
		'CN21I' => __( 'Dongfang' ),
		'CN21J' => __( 'Dingan' ),
		'CN21K' => __( 'Tunchang' ),
		'CN21L' => __( 'Chengmai' ),
		'CN21M' => __( 'Lingao' ),
		'CN21N' => __( 'Baisha Li Autonomous County' ),
		'CN21O' => __( 'Ledong Li Autonomous County' ),
		'CN21P' => __( 'Lingshui Li Autonomous County' ),
		'CN21Q' => __( 'Baoting Li and Miao Autonomous County' ),
		'CN21R' => __( 'Qiongzhong Li and Miao Autonomous County' ),
	),
	'CN22' => array(
		'CN22A' => __( 'Chongqing' ),
	),
	'CN23' => array(
		'CN23A' => __( 'Chengdu' ),
		'CN23B' => __( 'Zigong' ),
		'CN23C' => __( 'Panzhihua' ),
		'CN23D' => __( 'Luzhou' ),
		'CN23E' => __( 'Deyang' ),
		'CN23F' => __( 'Mianyang' ),
		'CN23G' => __( 'Guangyuan' ),
		'CN23H' => __( 'Suining' ),
		'CN23I' => __( 'Neijiang' ),
		'CN23J' => __( 'Leshan' ),
		'CN23K' => __( 'Nanchong' ),
		'CN23L' => __( 'Meishan' ),
		'CN23M' => __( 'Yibin' ),
		'CN23N' => __( "Guang'an" ),
		'CN23O' => __( 'Dazhou' ),
		'CN23P' => __( 'Yaan' ),
		'CN23Q' => __( 'Bazhong' ),
		'CN23R' => __( 'Ziyang' ),
		'CN23S' => __( 'Ngawa Tibetan and Qiang Autonomous Prefecture' ),
		'CN23T' => __( 'Garze Tibetan Autonomous Prefecture' ),
		'CN23U' => __( 'Liangshan Yi Autonomous Prefecture' ),
	),
	'CN24' => array(
		'CN24A' => __( 'Guiyang' ),
		'CN24B' => __( 'Liupanshui' ),
		'CN24C' => __( 'Zunyi' ),
		'CN24D' => __( 'Anshun' ),
		'CN24E' => __( 'Tongren' ),
		'CN24F' => __( 'Qianxinan Buyei and Miao Autonomous Prefecture' ),
		'CN24G' => __( 'Bijie' ),
		'CN24H' => __( 'Qiandongnan Miao and Dong Autonomous Prefecture' ),
		'CN24I' => __( 'Qiannan Buyei and Miao Autonomous Prefecture' ),
	),
	'CN25' => array(
		'CN25A' => __( 'Kunming' ),
		'CN25B' => __( 'Qujing' ),
		'CN25C' => __( 'Yuxi' ),
		'CN25D' => __( 'Baoshan' ),
		'CN25E' => __( 'Zhaotong' ),
		'CN25F' => __( 'Lijiang' ),
		'CN25G' => __( "Pu'er" ),
		'CN25H' => __( 'Lincang' ),
		'CN25I' => __( 'Chuxiong Yi Autonomous Prefecture' ),
		'CN25J' => __( 'Honghe Hani and Yi Autonomous Prefecture' ),
		'CN25K' => __( 'Wenshan Zhuang Autonomous Prefecture' ),
		'CN25L' => __( 'Xishuangbanna Dai Autonomous Prefecture' ),
		'CN25M' => __( 'Dali Bai Autonomous Prefecture' ),
		'CN25N' => __( 'Dehong Dai and Jingpo Autonomous Prefecture' ),
		'CN25O' => __( 'Nujiang Lisu Autonomous Prefecture' ),
		'CN25P' => __( 'Diqing Tibetan Autonomous Prefecture' ),
	),
	'CN26' => array(
		'CN26A' => __( 'Lhasa' ),
		'CN26B' => __( 'Chamdo' ),
		'CN26C' => __( 'Shannan' ),
		'CN26D' => __( 'Shigatse' ),
		'CN26E' => __( 'Nagqu Prefecture' ),
		'CN26F' => __( 'Ngari Prefecture' ),
		'CN26G' => __( 'Nyingchi' ),
	),
	'CN27' => array(
		'CN27A' => __( "Xi'an" ),
		'CN27B' => __( 'Tongchuan' ),
		'CN27C' => __( 'Baoji' ),
		'CN27D' => __( 'Xianyang' ),
		'CN27E' => __( 'Weinan' ),
		'CN27F' => __( "Yan'an" ),
		'CN27G' => __( 'Hanzhong' ),
		'CN27E' => __( 'Yulin' ),
		'CN27F' => __( 'Ankang' ),
		'CN27G' => __( 'Shangluo' ),
	),
	'CN28' => array(
		'CN28A' => __( 'Lanzhou' ),
		'CN28B' => __( 'Jiayuguan' ),
		'CN28C' => __( 'Jinchang' ),
		'CN28D' => __( 'Baiyin' ),
		'CN28E' => __( 'Tianshui' ),
		'CN28F' => __( 'Wuwei' ),
		'CN28G' => __( 'Zhangye' ),
		'CN28E' => __( 'Pingliang' ),
		'CN28F' => __( 'Jiuquan' ),
		'CN28G' => __( 'Qingyang' ),
		'CN28H' => __( 'Dingxi' ),
		'CN28I' => __( 'Longnan' ),
		'CN28J' => __( 'Linxia' ),
		'CN28K' => __( 'Gannan Tibetan Autonomous Prefecture' ),
	),
	'CN29' => array(
		'CN29A' => __( 'Xining' ),
		'CN29B' => __( 'Haidong' ),
		'CN29C' => __( 'Haibei Tibetan Autonomous Prefecture' ),
		'CN29D' => __( 'Huangnan Tibetan Autonomous Prefecture' ),
		'CN29E' => __( 'Hainan Tibetan Autonomous Prefecture' ),
		'CN29F' => __( 'Guoluo Tibetan Autonomous Prefecture' ),
		'CN29G' => __( 'Yushu Tibetan Autonomous Prefecture' ),
		'CN29E' => __( 'Haixi Mongol and Tibetan Autonomous Prefecture' ),
	),
	'CN30' => array(
		'CN30A' => __( 'Yinchuan' ),
		'CN30B' => __( 'Shizuishan' ),
		'CN30C' => __( 'Wuzhong' ),
		'CN30D' => __( 'Guyuan' ),
		'CN30E' => __( 'Zhongwei' ),
	),
	'CN31' => array(
		'CN31A' => __( 'Urumqi' ),
		'CN31B' => __( 'Karamay' ),
		'CN31C' => __( 'Turpan' ),
		'CN31D' => __( 'Hami' ),
		'CN31E' => __( 'Changji' ),
		'CN31F' => __( 'Bortala Mongol Autonomous Prefecture' ),
		'CN31G' => __( 'Bayingolin Mongol Autonomous Prefecture' ),
		'CN31E' => __( 'Aksu' ),
		'CN31F' => __( 'Kizilsu Kirghiz Autonomous Prefecture' ),
		'CN31G' => __( 'Kashgar' ),
		'CN31H' => __( 'Hotan' ),
		'CN31I' => __( 'Ili Kazakh Autonomous Prefecture' ),
		'CN31J' => __( 'Tacheng' ),
		'CN31K' => __( 'Altay' ),
		'CN31L' => __( 'Kokdala' ),
		'CN31M' => __( 'Shihezi' ),
		'CN31N' => __( 'Aral' ),
		'CN31O' => __( 'Tumxuk' ),
		'CN31P' => __( 'Wujiaqu' ),
	),
	'CN32' => array(

		'CN32A' => __( 'Taipei City' ),
		'CN32B' => __( 'Kaohsiung City' ),
		'CN32C' => __( 'Tainan City' ),
		'CN32D' => __( 'Taichung City' ),
		'CN32E' => __( 'Nantou County' ),
		'CN32F' => __( 'Keelung City' ),
		'CN32G' => __( 'Hsinchu City' ),
		'CN32H' => __( 'Chiayi City' ),
		'CN32I' => __( 'New Taipei City' ),
		'CN32J' => __( 'Yilan County' ),
		'CN32K' => __( 'Hsinchu County' ),
		'CN32L' => __( 'Taoyuan City' ),
		'CN32M' => __( 'Miaoli County' ),
		'CN32N' => __( 'Changhua County' ),
		'CN32O' => __( 'Chiayi County' ),
		'CN32P' => __( 'Yunlin County' ),
		'CN32Q' => __( 'Pingtung County' ),
		'CN32R' => __( 'Taitung County' ),
		'CN32S' => __( 'Hualien County' ),
		'CN32T' => __( 'Penghu-Inseln' ),
		'CN32U' => __( 'Other' ),
  		
	),
	'CN33' => array(
		'CN33A' => __( 'Hong Kong Island' ),
		'CN33B' => __( 'Kowloon' ),
		'CN33C' => __( 'New Territories' ),
	),
	'CN34' => array(
		'CN34A' => __( 'Macau Peninsula' ),
		'CN34B' => __( 'Taipa' ),
		'CN34C' => __( 'Cotai' ),
		'CN34D' => __( 'Coloane' ),
	)
);
