<?php
/**
 * Colombian cities
 */
global $cities;

$cities['CO'] = array(
	'AMA' => array(
		'Leticia',
		'Puerto Nariño'
	),
	'ANT' => array(
		'Abejorral',
		'Abriaquí',
		'Alejandria',
		'Amagá',
		'Amalfi',
		'Andes',
		'Angelópolis',
		'Angostura',
		'Anorí',
		'Anzá',
		'Apartadó',
		'Arboletes',
		'Argelia',
		'Armenia',
		'Barbosa',
		'Bello',
		'Belmira',
		'Betania',
		'Betulia',
		'Bolívar',
		'Briceño',
		'Burítica',
		'Cáceres',
		'Caicedo',
		'Caldas',
		'Campamento',
		'Cañasgordas',
		'Caracolí',
		'Caramanta',
		'Carepa',
		'Carmen de Viboral',
		'Carolina',
		'Caucasia',
		'Chigorodó',
		'Cisneros',
		'Cocorná',
		'Concepción',
		'Concordia',
		'Copacabana',
		'Dabeiba',
		'Don Matías',
		'Ebéjico',
		'El Bagre',
		'Entrerríos',
		'Envigado',
		'Fredonia',
		'Frontino',
		'Giraldo',
		'Girardota',
		'Gómez Plata',
		'Granada',
		'Guadalupe',
		'Guarne',
		'Guatapé',
		'Heliconia',
		'Hispania',
		'Itagüí',
		'Ituango',
		'Jardín',
		'Jericó',
		'La Ceja',
		'La Estrella',
		'La Pintada',
		'La Unión',
		'Liborina',
		'Maceo',
		'Marinilla',
		'Medellín',
		'Montebello',
		'Murindó',
		'Mutatá',
		'Nariño',
		'Nechí',
		'Necoclí',
		'Olaya',
		'Peñol',
		'Peque',
		'Pueblorrico',
		'Puerto Berrío',
		'Puerto Nare',
		'Puerto Triunfo',
		'Remedios',
		'Retiro',
		'Ríonegro',
		'Sabanalarga',
		'Sabaneta',
		'Salgar',
		'San Andrés de Cuerquía',
		'San Carlos',
		'San Francisco',
		'San Jerónimo',
		'San José de Montaña',
		'San Juan de Urabá',
		'San Luís',
		'San Pedro',
		'San Pedro de Urabá',
		'San Rafael',
		'San Roque',
		'San Vicente',
		'Santa Bárbara',
		'Santa Fé de Antioquia',
		'Santa Rosa de Osos',
		'Santo Domingo',
		'Santuario',
		'Segovia',
		'Sonsón',
		'Sopetrán',
		'Támesis',
		'Tarazá',
		'Tarso',
		'Titiribí',
		'Toledo',
		'Turbo',
		'Uramita',
		'Urrao',
		'Valdivia',
		'Valparaiso',
		'Vegachí',
		'Venecia',
		'Vigía del Fuerte',
		'Yalí',
		'Yarumal',
		'Yolombó',
		'Yondó (Casabe)',
		'Zaragoza'
	),
	'ARA' => array(
		'Arauca',
		'Arauquita',
		'Cravo Norte',
		'Fortúl',
		'Puerto Rondón',
		'Saravena',
		'Tame'
	),
	'ATL' => array(
		'Baranoa',
		'Barranquilla',
		'Campo de la Cruz',
		'Candelaria',
		'Galapa',
		'Juan de Acosta',
		'Luruaco',
		'Malambo',
		'Manatí',
		'Palmar de Varela',
		'Piojo',
		'Polonuevo',
		'Ponedera',
		'Puerto Colombia',
		'Repelón',
		'Sabanagrande',
		'Sabanalarga',
		'Santa Lucía',
		'Santo Tomás',
		'Soledad',
		'Suan',
		'Tubará',
		'Usiacuri'
	),
	'BOL' => array(
		'Achí',
		'Altos del Rosario',
		'Arenal',
		'Arjona',
		'Arroyohondo',
		'Barranco de Loba',
		'Calamar',
		'Cantagallo',
		'Cartagena',
		'Cicuco',
		'Clemencia',
		'Córdoba',
		'El Carmen de Bolívar',
		'El Guamo',
		'El Peñon',
		'Hatillo de Loba',
		'Magangué',
		'Mahates',
		'Margarita',
		'María la Baja',
		'Mompós',
		'Montecristo',
		'Morales',
		'Norosí',
		'Pinillos',
		'Regidor',
		'Río Viejo',
		'San Cristobal',
		'San Estanislao',
		'San Fernando',
		'San Jacinto',
		'San Jacinto del Cauca',
		'San Juan de Nepomuceno',
		'San Martín de Loba',
		'San Pablo',
		'Santa Catalina',
		'Santa Rosa',
		'Santa Rosa del Sur',
		'Simití',
		'Soplaviento',
		'Talaigua Nuevo',
		'Tiquisio (Puerto Rico)',
		'Turbaco',
		'Turbaná',
		'Villanueva',
		'Zambrano'
	),
	'BOY' => array(
		'Almeida',
		'Aquitania',
		'Arcabuco',
		'Belén',
		'Berbeo',
		'Beteitiva',
		'Boavita',
		'Boyacá',
		'Briceño',
		'Buenavista',
		'Busbanza',
		'Caldas',
		'Campohermoso',
		'Cerinza',
		'Chinavita',
		'Chiquinquirá',
		'Chíquiza',
		'Chiscas',
		'Chita',
		'Chitaraque',
		'Chivatá',
		'Chívor',
		'Ciénaga',
		'Cómbita',
		'Coper',
		'Corrales',
		'Covarachía',
		'Cubará',
		'Cucaita',
		'Cuitiva',
		'Duitama',
		'El Cocuy',
		'El Espino',
		'Firavitoba',
		'Floresta',
		'Gachantivá',
		'Gámeza',
		'Garagoa',
		'Guacamayas',
		'Guateque',
		'Guayatá',
		'Guicán',
		'Izá',
		'Jenesano',
		'Jericó',
		'La Capilla',
		'La Uvita',
		'La Victoria',
		'Labranzagrande',
		'Macanal',
		'Maripí',
		'Miraflores',
		'Mongua',
		'Monguí',
		'Moniquirá',
		'Motavita',
		'Muzo',
		'Nobsa',
		'Nuevo Colón',
		'Oicatá',
		'Otanche',
		'Pachavita',
		'Páez',
		'Paipa',
		'Pajarito',
		'Panqueba',
		'Pauna',
		'Paya',
		'Paz de Río',
		'Pesca',
		'Pisva',
		'Puerto Boyacá',
		'Quipama',
		'Ramiriquí',
		'Ráquira',
		'Rondón',
		'Saboyá',
		'Sáchica',
		'Samacá',
		'San Eduardo',
		'San José de Pare',
		'San Luís de Gaceno',
		'San Mateo',
		'San Miguel de Sema',
		'San Pablo de Borbur',
		'Santa María',
		'Santa Rosa de Viterbo',
		'Santa Sofía',
		'Santana',
		'Sativanorte',
		'Sativasur',
		'Siachoque',
		'Soatá',
		'Socha',
		'Socotá',
		'Sogamoso',
		'Somondoco',
		'Sora',
		'Soracá',
		'Sotaquirá',
		'Susacón',
		'Sutamarchán',
		'Sutatenza',
		'Tasco',
		'Tenza',
		'Tibaná',
		'Tibasosa',
		'Tinjacá',
		'Tipacoque',
		'Toca',
		'Toguí',
		'Topagá',
		'Tota',
		'Tunja',
		'Tunungua',
		'Turmequé',
		'Tuta',
		'Tutasá',
		'Úmbita',
		'Ventaquemada',
		'Villa de Leiva',
		'Viracachá',
		'Zetaquirá'
	),
	'CAL' => array(
		'Aguadas',
		'Anserma',
		'Aranzazu',
		'Belalcázar',
		'Chinchiná',
		'Filadelfia',
		'La Dorada',
		'La Merced',
		'La Victoria',
		'Manizales',
		'Manzanares',
		'Marmato',
		'Marquetalia',
		'Marulanda',
		'Neira',
		'Norcasia',
		'Pácora',
		'Palestina',
		'Pensilvania',
		'Río Sucio',
		'Risaralda',
		'Salamina',
		'Samaná',
		'San José',
		'Supía',
		'Villamaría',
		'Viterbo'
	),
	'CAQ' => array(
		'Albania',
		'Belén de los Andaquíes',
		'Cartagena del Chairá',
		'Curillo',
		'El Doncello',
		'El Paujil',
		'Florencia',
		'La Montañita',
		'Milán',
		'Morelia',
		'Puerto Rico',
		'San José del Fragua',
		'San Vicente del Caguán',
		'Solano',
		'Solita',
		'Valparaiso'
	),
	'CAS' => array(
		'Aguazul',
		'Chámeza',
		'Hato Corozal',
		'La Salina',
		'Maní',
		'Monterrey',
		'Nunchía',
		'Orocué',
		'Paz de Ariporo',
		'Pore',
		'Recetor',
		'Sabanalarga',
		'Sácama',
		'San Luís de Palenque',
		'Támara',
		'Tauramena',
		'Trinidad',
		'Villanueva',
		'Yopal'
	),
	'CAU' => array(
		'Almaguer',
		'Argelia',
		'Balboa',
		'Bolívar',
		'Buenos Aires',
		'Cajibío',
		'Caldono',
		'Caloto',
		'Corinto',
		'El Tambo',
		'Florencia',
		'Guachené',
		'Guapí',
		'Inzá',
		'Jambaló',
		'La Sierra',
		'La Vega',
		'López (Micay)',
		'Mercaderes',
		'Miranda',
		'Morales',
		'Padilla',
		'Páez (Belalcazar)',
		'Patía (El Bordo)',
		'Piamonte',
		'Piendamó',
		'Popayán',
		'Puerto Tejada',
		'Puracé (Coconuco)',
		'Rosas',
		'San Sebastián',
		'Santa Rosa',
		'Santander de Quilichao',
		'Silvia',
		'Sotara (Paispamba)',
		'Suárez',
		'Sucre',
		'Timbío',
		'Timbiquí',
		'Toribío',
		'Totoró',
		'Villa Rica'
	),
	'CES' => array(
		'Aguachica',
		'Agustín Codazzi',
		'Astrea',
		'Becerríl',
		'Bosconia',
		'Chimichagua',
		'Chiriguaná',
		'Curumaní',
		'El Copey',
		'El Paso',
		'Gamarra',
		'Gonzalez',
		'La Gloria',
		'La Jagua de Ibirico',
		'La Paz (Robles)',
		'Manaure Balcón del Cesar',
		'Pailitas',
		'Pelaya',
		'Pueblo Bello',
		'Río de oro',
		'San Alberto',
		'San Diego',
		'San Martín',
		'Tamalameque',
		'Valledupar'
	),
	'CHO' => array(
		'Acandí',
		'Alto Baudó (Pie de Pato)',
		'Atrato (Yuto)',
		'Bagadó',
		'Bahía Solano (Mútis)',
		'Bajo Baudó (Pizarro)',
		'Belén de Bajirá',
		'Bojayá (Bellavista)',
		'Cantón de San Pablo',
		'Carmen del Darién (CURBARADÓ)',
		'Cértegui',
		'Condoto',
		'El Carmen de Atrato',
		'Istmina',
		'Juradó',
		'Lloró',
		'Medio Atrato',
		'Medio Baudó',
		'Medio San Juan (ANDAGOYA)',
		'Novita',
		'Nuquí',
		'Quibdó',
		'Río Iró',
		'Río Quito',
		'Ríosucio',
		'San José del Palmar',
		'Santa Genoveva de Docorodó',
		'Sipí',
		'Tadó',
		'Unguía',
		'Unión Panamericana (ÁNIMAS)'
	),
	'COR' => array(
		'Ayapel',
		'Buenavista',
		'Canalete',
		'Cereté',
		'Chimá',
		'Chinú',
		'Ciénaga de Oro',
		'Cotorra',
		'La Apartada y La Frontera',
		'Lorica',
		'Los Córdobas',
		'Momil',
		'Moñitos',
		'Montelíbano',
		'Monteria',
		'Planeta Rica',
		'Pueblo Nuevo',
		'Puerto Escondido',
		'Puerto Libertador',
		'Purísima',
		'Sahagún',
		'San Andrés Sotavento',
		'San Antero',
		'San Bernardo del Viento',
		'San Carlos',
		'San José de Uré',
		'San Pelayo',
		'Tierralta',
		'Tuchín',
		'Valencia'
	),
	'CUN' => array(
		'Agua de Dios',
		'Albán',
		'Anapoima',
		'Anolaima',
		'Apulo',
		'Arbeláez',
		'Beltrán',
		'Bituima',
		'Bogotá D.C.',
		'Bojacá',
		'Cabrera',
		'Cachipay',
		'Cajicá',
		'Caparrapí',
		'Cáqueza',
		'Carmen de Carupa',
		'Chaguaní',
		'Chía',
		'Chipaque',
		'Choachí',
		'Chocontá',
		'Cogua',
		'Cota',
		'Cucunubá',
		'El Colegio',
		'El Peñón',
		'El Rosal',
		'Facatativá',
		'Fómeque',
		'Fosca',
		'Funza',
		'Fúquene',
		'Fusagasugá',
		'Gachalá',
		'Gachancipá',
		'Gachetá',
		'Gama',
		'Girardot',
		'Granada',
		'Guachetá',
		'Guaduas',
		'Guasca',
		'Guataquí',
		'Guatavita',
		'Guayabal de Siquima',
		'Guayabetal',
		'Gutiérrez',
		'Jerusalén',
		'Junín',
		'La Calera',
		'La Mesa',
		'La Palma',
		'La Peña',
		'La Vega',
		'Lenguazaque',
		'Machetá',
		'Madrid',
		'Manta',
		'Medina',
		'Mosquera',
		'Nariño',
		'Nemocón',
		'Nilo',
		'Nimaima',
		'Nocaima',
		'Pacho',
		'Paime',
		'Pandi',
		'Paratebueno',
		'Pasca',
		'Puerto Salgar',
		'Pulí',
		'Quebradanegra',
		'Quetame',
		'Quipile',
		'Ricaurte',
		'San Antonio de Tequendama',
		'San Bernardo',
		'San Cayetano',
		'San Francisco',
		'San Juan de Río Seco',
		'Sasaima',
		'Sesquilé',
		'Sibaté',
		'Silvania',
		'Simijaca',
		'Soacha',
		'Sopó',
		'Subachoque',
		'Suesca',
		'Supatá',
		'Susa',
		'Sutatausa',
		'Tabio',
		'Tausa',
		'Tena',
		'Tenjo',
		'Tibacuy',
		'Tibirita',
		'Tocaima',
		'Tocancipá',
		'Topaipí',
		'Ubalá',
		'Ubaque',
		'Ubaté',
		'Une',
		'Útica',
		'Venecia (Ospina Pérez)',
		'Vergara',
		'Viani',
		'Villagómez',
		'Villapinzón',
		'Villeta',
		'Viotá',
		'Yacopí',
		'Zipacón',
		'Zipaquirá'
	),
	'GUA' => array( 'Inírida' ),
	'GUV' => array(
		'Calamar',
		'El Retorno',
		'Miraflores',
		'San José del Guaviare'
	),
	'HUI' => array(
		'Acevedo',
		'Agrado',
		'Aipe',
		'Algeciras',
		'Altamira',
		'Baraya',
		'Campoalegre',
		'Colombia',
		'Elías',
		'Garzón',
		'Gigante',
		'Guadalupe',
		'Hobo',
		'Íquira',
		'Isnos',
		'La Argentina',
		'La Plata',
		'Nátaga',
		'Neiva',
		'Oporapa',
		'Paicol',
		'Palermo',
		'Palestina',
		'Pital',
		'Pitalito',
		'Rivera',
		'Saladoblanco',
		'San Agustín',
		'Santa María',
		'Suaza',
		'Tarqui',
		'Tello',
		'Teruel',
		'Tesalia',
		'Timaná',
		'Villavieja',
		'Yaguará'
	),
	'LAG' => array(
		'Albania',
		'Barrancas',
		'Dibulla',
		'Distracción',
		'El Molino',
		'Fonseca',
		'Hatonuevo',
		'La Jagua del Pilar',
		'Maicao',
		'Manaure',
		'Riohacha',
		'San Juan del Cesar',
		'Uribia',
		'Urumita',
		'Villanueva'
	),
	'MAG' => array(
		'Algarrobo',
		'Aracataca',
		'Ariguaní (El Difícil)',
		'Cerro San Antonio',
		'Chivolo',
		'Ciénaga',
		'Concordia',
		'El Banco',
		'El Piñon',
		'El Retén',
		'Fundación',
		'Guamal',
		'Nueva Granada',
		'Pedraza',
		'Pijiño',
		'Pivijay',
		'Plato',
		'Puebloviejo',
		'Remolino',
		'Sabanas de San Angel (SAN ANGEL)',
		'Salamina',
		'San Sebastián de Buenavista',
		'San Zenón',
		'Santa Ana',
		'Santa Bárbara de Pinto',
		'Santa Marta',
		'Sitionuevo',
		'Tenerife',
		'Zapayán (PUNTA DE PIEDRAS)',
		'Zona Bananera (PRADO - SEVILLA)'
	),
	'MET' => array(
		'Acacías',
		'Barranca de Upía',
		'Cabuyaro',
		'Castilla la Nueva',
		'Cubarral',
		'Cumaral',
		'El Calvario',
		'El Castillo',
		'El Dorado',
		'Fuente de Oro',
		'Granada',
		'Guamal',
		'La Macarena',
		'Lejanías',
		'Mapiripan',
		'Mesetas',
		'Puerto Concordia',
		'Puerto Gaitán',
		'Puerto Lleras',
		'Puerto López',
		'Puerto Rico',
		'Restrepo',
		'San Carlos de Guaroa',
		'San Juan de Arama',
		'San Juanito',
		'San Martín',
		'Uribe',
		'Villavicencio',
		'Vista Hermosa'
	),
	'NAR' => array(
		'Albán (San José)',
		'Aldana',
		'Ancuya',
		'Arboleda (Berruecos)',
		'Barbacoas',
		'Belén',
		'Buesaco',
		'Chachaguí',
		'Colón (Génova)',
		'Consaca',
		'Contadero',
		'Córdoba',
		'Cuaspud (Carlosama)',
		'Cumbal',
		'Cumbitara',
		'El Charco',
		'El Peñol',
		'El Rosario',
		'El Tablón de Gómez',
		'El Tambo',
		'Francisco Pizarro',
		'Funes',
		'Guachavés',
		'Guachucal',
		'Guaitarilla',
		'Gualmatán',
		'Iles',
		'Imúes',
		'Ipiales',
		'La Cruz',
		'La Florida',
		'La Llanada',
		'La Tola',
		'La Unión',
		'Leiva',
		'Linares',
		'Magüi (Payán)',
		'Mallama (Piedrancha)',
		'Mosquera',
		'Nariño',
		'Olaya Herrera',
		'Ospina',
		'Policarpa',
		'Potosí',
		'Providencia',
		'Puerres',
		'Pupiales',
		'Ricaurte',
		'Roberto Payán (San José)',
		'Samaniego',
		'San Bernardo',
		'San Juan de Pasto',
		'San Lorenzo',
		'San Pablo',
		'San Pedro de Cartago',
		'Sandoná',
		'Santa Bárbara (Iscuandé)',
		'Sapuyes',
		'Sotomayor (Los Andes)',
		'Taminango',
		'Tangua',
		'Tumaco',
		'Túquerres',
		'Yacuanquer'
	),
	'NSA' => array(
		'Ábrego',
		'Arboledas',
		'Bochalema',
		'Bucarasica',
		'Cáchira',
		'Cácota',
		'Chinácota',
		'Chitagá',
		'Convención',
		'Cúcuta',
		'Cucutilla',
		'Durania',
		'El Carmen',
		'El Tarra',
		'El Zulia',
		'Gramalote',
		'Hacarí',
		'Herrán',
		'La Esperanza',
		'La Playa',
		'Labateca',
		'Los Patios',
		'Lourdes',
		'Mutiscua',
		'Ocaña',
		'Pamplona',
		'Pamplonita',
		'Puerto Santander',
		'Ragonvalia',
		'Salazar',
		'San Calixto',
		'San Cayetano',
		'Santiago',
		'Sardinata',
		'Silos',
		'Teorama',
		'Tibú',
		'Toledo',
		'Villa Caro',
		'Villa del Rosario'
	),
	'PUT' => array(
		'Colón',
		'Mocoa',
		'Orito',
		'Puerto Asís',
		'Puerto Caicedo',
		'Puerto Guzmán',
		'Puerto Leguízamo',
		'San Francisco',
		'San Miguel',
		'Santiago',
		'Sibundoy',
		'Valle del Guamuez',
		'Villagarzón'
	),
	'QUI' => array(
		'Armenia',
		'Buenavista',
		'Calarcá',
		'Circasia',
		'Cordobá',
		'Filandia',
		'Génova',
		'La Tebaida',
		'Montenegro',
		'Pijao',
		'Quimbaya',
		'Salento'
	),
	'RIS' => array(
		'Apía',
		'Balboa',
		'Belén de Umbría',
		'Dos Quebradas',
		'Guática',
		'La Celia',
		'La Virginia',
		'Marsella',
		'Mistrató',
		'Pereira',
		'Pueblo Rico',
		'Quinchía',
		'Santa Rosa de Cabal',
		'Santuario'
	),
	'SAP' => array( 'Providencia' ),
	'SAN' => array(
		'Aguada',
		'Albania',
		'Aratoca',
		'Barbosa',
		'Barichara',
		'Barrancabermeja',
		'Betulia',
		'Bolívar',
		'Bucaramanga',
		'Cabrera',
		'California',
		'Capitanejo',
		'Carcasí',
		'Cepita',
		'Cerrito',
		'Charalá',
		'Charta',
		'Chima',
		'Chipatá',
		'Cimitarra',
		'Concepción',
		'Confines',
		'Contratación',
		'Coromoro',
		'Curití',
		'El Carmen',
		'El Guacamayo',
		'El Peñon',
		'El Playón',
		'Encino',
		'Enciso',
		'Florián',
		'Floridablanca',
		'Galán',
		'Gámbita',
		'Girón',
		'Guaca',
		'Guadalupe',
		'Guapota',
		'Guavatá',
		'Guepsa',
		'Hato',
		'Jesús María',
		'Jordán',
		'La Belleza',
		'La Paz',
		'Landázuri',
		'Lebrija',
		'Los Santos',
		'Macaravita',
		'Málaga',
		'Matanza',
		'Mogotes',
		'Molagavita',
		'Ocamonte',
		'Oiba',
		'Onzaga',
		'Palmar',
		'Palmas del Socorro',
		'Páramo',
		'Pie de Cuesta',
		'Pinchote',
		'Puente Nacional',
		'Puerto Parra',
		'Puerto Wilches',
		'Rio Negro',
		'Sabana de Torres',
		'San Andrés',
		'San Benito',
		'San Gíl',
		'San Joaquín',
		'San José de Miranda',
		'San Miguel',
		'San Vicente del Chucurí',
		'Santa Bárbara',
		'Santa Helena del Opón',
		'Simacota',
		'Socorro',
		'Suaita',
		'Sucre',
		'Suratá',
		'Tona',
		'Valle de San José',
		'Vélez',
		'Vetas',
		'Villanueva',
		'Zapatoca'
	),
	'SUC' => array(
		'Buenavista',
		'Caimito',
		'Chalán',
		'Colosó (Ricaurte)',
		'Corozal',
		'Coveñas',
		'El Roble',
		'Galeras (Nueva Granada)',
		'Guaranda',
		'La Unión',
		'Los Palmitos',
		'Majagual',
		'Morroa',
		'Ovejas',
		'Palmito',
		'Sampués',
		'San Benito Abad',
		'San Juan de Betulia',
		'San Marcos',
		'San Onofre',
		'San Pedro',
		'Sincé',
		'Sincelejo',
		'Sucre',
		'Tolú',
		'Tolú Viejo'
	),
	'TOL' => array(
		'Alpujarra',
		'Alvarado',
		'Ambalema',
		'Anzoátegui',
		'Armero (Guayabal)',
		'Ataco',
		'Cajamarca',
		'Carmen de Apicalá',
		'Casabianca',
		'Chaparral',
		'Coello',
		'Coyaima',
		'Cunday',
		'Dolores',
		'Espinal',
		'Falan',
		'Flandes',
		'Fresno',
		'Guamo',
		'Herveo',
		'Honda',
		'Ibagué',
		'Icononzo',
		'Lérida',
		'Líbano',
		'Mariquita',
		'Melgar',
		'Murillo',
		'Natagaima',
		'Ortega',
		'Palocabildo',
		'Piedras',
		'Planadas',
		'Prado',
		'Purificación',
		'Rioblanco',
		'Roncesvalles',
		'Rovira',
		'Saldaña',
		'San Antonio',
		'San Luis',
		'Santa Isabel',
		'Suárez',
		'Valle de San Juan',
		'Venadillo',
		'Villahermosa',
		'Villarrica'
	),
	'VAC' => array(
		'Alcalá',
		'Andalucía',
		'Ansermanuevo',
		'Argelia',
		'Bolívar',
		'Buenaventura',
		'Buga',
		'Bugalagrande',
		'Caicedonia',
		'Cali',
		'Calima (Darién)',
		'Candelaria',
		'Cartago',
		'Dagua',
		'El Águila',
		'El Cairo',
		'El Cerrito',
		'El Dovio',
		'Florida',
		'Ginebra',
		'Guacarí',
		'Jamundí',
		'La Cumbre',
		'La Unión',
		'La Victoria',
		'Obando',
		'Palmira',
		'Pradera',
		'Restrepo',
		'Riofrío',
		'Roldanillo',
		'San Pedro',
		'Sevilla',
		'Toro',
		'Trujillo',
		'Tulúa',
		'Ulloa',
		'Versalles',
		'Vijes',
		'Yotoco',
		'Yumbo',
		'Zarzal'
	),
	'VAU' => array(
		'Carurú',
		'Mitú',
		'Taraira'
	),
	'VID' => array(
		'Cumaribo',
		'La Primavera',
		'Puerto Carreño',
		'Santa Rosalía'
	),
);
