<?php
/*
* Ecuadorian Cities
*/
global $cities;

$cities['EC'] = array(
    'Azuay' => array(
        'Cuenca',
        'Chaullabamba',
        'Gualaceo',
        'Chordeleg',
        'Sigsig',
        'Paute',
        'Zona Franca',
        'Cumbe',
        'Tarqui',
        'Girón',
        'Santa Isabel',
        'Oña',
        'Saraguro'
    ),
    'Bolivar' => array(
        'GUARANDA',
        'Chillanes',
        'Salinas de Guaranda',
        'San Pedro de Guanujo',
        'San Jose de Chimbo',
        'San Miguel de Bolívar'
    ),
    'Canar' => array(
        'AZOGUES',
        'Biblian',
        'Cañar',
        'Cojitambo',
        'Deleg',
        'El Tambo'
    ),
    'Carchi' => array(
        'Tulcán',
        'San Gabriel',
        'El Angel',
        'Julio Andrade',
        'Bolívar',
        'Huaca',
        'Mira'
    ),
    'Chimborazo' => array(
        'Riobamba',
        'Guano',
        'Cajabamba',
        'Chambo',
        'Chunchi',
        'Lican',
        'Yaruquies',
        'Alausi',
        'Guamote',
        'Colta'
    ),
    'Cotopaxi' => array(
        'Latacunga',
        'Salcedo',
        'Guaytacama',
        'Pastocalle',
        'Mulalo',
        'Tanicuchi',
        'Belisario Quevedo',
        'Saquisili',
        'Pujili',
        'Lasso'
    ),
    'ElOro' => array(
        'MACHALA',
        'Arenillas',
        'El Cambio',
        'El Guabo',
        'Huaquillas',
        'La Iberia',
        'Pasaje',
        'Marcabelí',
        'Balsas',
        'Piñas',
        'Portovelo',
        'Puerto Bolívar',
        'Santa Rosa',
        'Zaruma'
    ),
    'Esmeraldas' => array(
        'Esmeraldas',
        'Tonsupa',
        'Atacames',
        'Tachina',
        'Same',
        'Tonchigue',
        'El Salto',
        'Mompiche',
        'Muisne',
        'La Pradera',
        'Sua',
        'QUININDE',
        'Viche',
        'Las Golondrinas'
    ),
    'Galapagos' => array(
        'San Cristóbal',
        'Santa Cruz'
    ),
    'Guayas' => array(
        'Guayaquil',
        'Duran',
        'Nobol',
        'Isidro ayora',
        'Lomas de Sargentillo',
        'Pedro Carbo',
        'Cerecita',
        'Chongon',
        'Playas',
        'Posorja',
        'Progreso',
        'Palestina',
        'Colimes',
        'Santa Lucia',
        'Balzar',
        'Laurel',
        'Salitre',
        'Samborondon',
        'Chiveria',
        'Petrillo',
        'Puente Lucia',
        'Coloradal',
        'General Vernaza',
        'La Maravilla',
        'Las Animas',
        'Los Tintos',
        'Sabanilla',
        'Tarifa',
        'Milagro',
        'Bucay',
        'Manuel J. Calle',
        'Cochancay',
        'Yaguachi',
        'El Triunfo',
        'Km 26 via Duran Tambo',
        'La Troncal',
        'Naranjito',
        'Base Taura',
        'Simon Bolivar',
        'Cumanda',
        'Roberto Astudillo',
        'Marcelino Maridueña',
        'El Deseo',
        'Matilde Esther',
        'Mariscal Sucre',
        'Lorenzo de Garaicoa',
        'Naranjal',
        'Balao',
        'Tenguel'
    ),
    'Imbabura' => array(
        'Ibarra',
        'Aduana(Yaguarcocha)',
        'Caranqui',
        'Chorlaví',
        'San Antonio de Ibarra',
        'Yaguarcocha',
        'Urcuqui',
        'Atuntaqui',
        'Andrade Marin',
        'Chaltura',
        'San Luis',
        'La Merced',
        'Santa Bertha',
        'Pimampiro',
        'Tierra Blanca',
        'San Jose',
        'Natabuela',
        'Antonio Ante',
        'OTAVALO',
        'Cotacachi',
        'San Roque',
        'San Pablo',
        'Gonzalez Suarez',
        'Perugachi',
        'Peguche',
        'Quiroga'
    ),
    'Loja' => array(
        'Loja',
        'Alamor',
        'Cariamanga',
        'Catacocha',
        'Catamayo',
        'Celica',
        'Gonzanama',
        'Vilcabamba (Dentro de Perímetro Urbano)',
        'Macará'
    ),
    'LosRios' => array(
        'Babahoyo',
        'Baba',
        'Caluma',
        'Catarama',
        'Jujan',
        'Montalvo',
        'Palenque',
        'Pueblo Viejo',
        'Ricaurte',
        'San Juan',
        'Tres Postes',
        'Ventanas',
        'Vinces',
        'Echeandia',
        'QUEVEDO',
        'Buena Fe',
        'El Empalme',
        'La Mana',
        'Mocache',
        'Quinsaloma',
        'San Camilo',
        'San Carlos',
        'Valencia'
    ),
    'Manabi' => array(
        'El Carmen',
        'Pedernales',
        'Chone',
        'Calceta',
        'Canuto',
        'Estancilla',
        'Flavio Alfaro',
        'Ricaurte',
        'San Antonio de Chone',
        'Junin',
        'Tosagua',
        'Bahía de Caraquez',
        'Leonidas Plaza',
        'San Vicente',
        'Jama',
        'MANTA',
        'Montecristi',
        'Jaramijo',
        'Jipijapa',
        'Pajan',
        'Puerto Cayo',
        'Puerto Lopez',
        'PORTOVIEJO',
        'Alahuela',
        'Calderon',
        'Charapoto',
        'Colon',
        'Crucita',
        'Picoaza (Dentro del perímetro Urbano)',
        'San Plácido (Dentro del perímetro Urbano)',
        'Rio Chico (Dentro del perímetro Urbano)',
        'Rocafuerte',
        '24 de Mayo',
        'Olmedo',
        'Santa Ana',
        'Pichincha',
    ),
    'Morona' => array(
        'Macas',
        'Mendez',
        'Limon',
        'Sucua',
        'Gualaquiza'
    ),
    'Napo' => array(
        'Tena',
        'Archidona',
        'Pto. Napo',
        'Misahualli',
        'Arosemena Tola',
        'El Chaco'
    ),
    'Orellana' => array(
        'Tena',
        'Archidona',
        'Pto. Napo',
        'Misahualli',
        'Arosemena Tola',
        'El Chaco',
    ),
    'Pastaza' => array(
        'Puyo',
        'Shell',
        'Mera',
        'Palora',
        'Santa Clara'
    ),
    'Pichincha' => array(
        'Cayambe',
        'Ayora',
        'Cuzubamba',
        'Juan Montalvo',
        'Tabacundo/Pedro Moncayo',
        'QUITO',
        'Alangasi',
        'Aloag',
        'Aloasi',
        'Amaguaña',
        'Azcasubi vía al Quinche',
        'Calderón',
        'Conocoto',
        'Cumbaya',
        'Cusubamba',
        'Guayllabamba',
        'La Armenia',
        'Llano Chico',
        'Llano Grande',
        'Machachi',
        'Mariana',
        'Miravalle',
        'Mitad del Mundo',
        'Monjas',
        'Orquideas',
        'Pifo',
        'Pintag',
        'Pomasqui',
        'Puembo',
        'Pusuqui',
        'Quinche',
        'San Antonio de Pichincha',
        'San Jose de Moran',
        'San Juan de Calderon',
        'San Rafael',
        'Sangolqui',
        'Tababela',
        'Tambillo',
        'Tumbaco',
        'Uyumbicho',
        'Valle de los Chillos',
        'Yaruqui',
        'Zambisa',
        'Puerto Quito',
        'Pedro V. Maldonado',
        'San Miguel de Bancos',
        'Nanegalito',
        'Calacaquili',
    ),
    'SantaElena' => array(
        'Salinas',
        'La Libertad',
        'Santa Elena',
        'Muey',
        'Puerto Santa Rosa',
        'Ancon',
        'Anconcito',
        'Mar Bravo',
        'Punta Carnero',
        'Ballenita',
        'Manglaralto',
        'Montañita',
        'Olón',
        'San Pablo',
        'Punta Blanca',
        'Cadeate',
        'Capaes',
        'Libertador Bolivar',
        'Monteverde',
        'Palmar',
        'Prosperidad',
        'Punta Barandua',
        'San Pedro',
        'Valdivia'
    ),
    'SantoDomingo' => array(
        'Santo Domingo',
        'Alluriquin',
        'Km 14-Quevedo',
        'Km 24-Quevedo',
        'Km 38.5-Quevedo',
        'Km 41-Quevedo',
        'Luz de America',
        'Patricia Pilar',
        'Puerto Limón',
        'San Jacinto del Búa',
        'LA CONCORDIA',
        'La Independencia',
        'Las Villegas',
        'Monterrey',
        'La Union',
        'Valle Hermoso',
        'Nuevo Israel',
        'La Delicia Km. 29'
    ),
    'Sucumbios' => array(
        'Lago Agrio',
        'Shushufindi',
        'Nueva Loja',
        'Cascales',
        'Lumbaqui'
    ),
    'Tungurahua' => array(
        'Ambato',
        'Mocha',
        'Cevallos',
        'Quero',
        'Tisaleo',
        'Baños de Agua Santa',
        'Pelileo',
        'Patate',
        'Pillaro'
    ),
    'Zamora' => array(
        'Zamora',
        'Centinela del Condor',
        'Cumbaratza',
        'Yantzaza'

    )
);