<?php
/**
 * Egyptian cities
 */
global $cities;

$cities['EG'] = array(
        'EGC' => array(
            'Ain Shams',
            'Al Azhar',
            'Al Daher',
            'Al Kalaa',
            'Al Kasr Al Einy',
            'Al Matareya',
            'Al Moski',
            'Al Rehab',
            'Al Salam City',
            'Al Zeitoun',
            'Almaza',
            'Amiria',
            'Badr City',
            'Cornish Al Nile',
            'Dar Al Salam',
            'Down Town',
            'El Herafieen',
            'EL Marg',
            'El Shorouk',
            'El Tahrir',
            'Ezbet El Nakhl',
            'Fustat',
            'Garden City',
            'Gesr Al Suez',
            'Ghamrah',
            'Hadayek Al Qobah',
            'Hadayek Al Zaiton',
            'Hadayek Helwan',
            'Hadayek Maadi',
            'Heliopolis',
            'Helmeya',
            'Helmiet Elzaitoun',
            'Helwan',
            'Katamiah',
            'Maadi',
            'Maadi Degla',
            'Madinty',
            'Manial Al Rodah',
            'Masaken Sheraton',
            'Mirage City',
            'Misr El Kadima',
            'Mokattam',
            'Nasr City',
            'New Cairo',
            'New El Marg',
            'New Maadi',
            'New Nozha',
            'Ramsis',
            'Rod El Farag',
            'Sayeda Zeinab',
            'Shubra',
            'Zamalek'
        ),
        'EGSHR' => array(
            '10th of Ramdan City',
            'Abu Hammad',
            'Abu Kbeer',
            'Al Hasiniya',
            'Al Ibrahimiya',
            'Al Salhiya Al Gedida',
            'Al Sharqia',
            'Awlad Saqr',
            'Belbes',
            'Darb Negm',
            'Faqous',
            'Hehya',
            'Kafr Saqr',
            'Mashtool Al Sooq',
            'Meniya Alqamh',
            'Zakazik'
        ),
        'EGALX' => array(
            'Abees',
            'Abu Keer',
            'Al Amriah',
            'Al Bitash',
            'Al Nahda Al Amria',
            'Al Soyof',
            'Alexandria',
            'Asafra',
            'Awaied-Ras Souda',
            'Azarita',
            'Bangar EL Sokar',
            'Borg El Arab',
            'City Center',
            'El Borg El Kadem',
            'El-Agamy',
            'Glem',
            'Kafer Abdou',
            'Khorshid',
            'Luran',
            'Maamora',
            'Mahtet El-Raml',
            'Mandara',
            'Manshia',
            'Miami',
            'Muntazah',
            'Roshdy',
            'San Stefano',
            'Sedi Bisher',
            'Sedi Gaber',
            'Sedi Kreir',
            'Smouha',
            'Sporting',
            'Stanly',
            'Zezenya'
        ),
        'EGGZ' => array(
            '6th of October',
            'Agouza',
            'Al Kom Al Ahmer',
            'Al Moatamadia',
            'Al Monib',
            'Al Nobariah',
            'Bolak Al Dakrour',
            'Dokki',
            'Faisal',
            'Giza',
            'Hadayeq El Ahram',
            'Haram',
            'Imbaba',
            'Kit Kat',
            'Manial',
            'Mohandessin',
            'Omraneya',
            'Qism el Giza',
            'Sakiat Mekki',
            'Sheikh Zayed',
            'Smart Village',
            'Tirsa',
            'Warraq'
        ),
        'EGAST' => array(
            'Abnoub',
            'Abou Teag',
            'Assuit Elgdeda',
            'Asyut',
            'Dayrout',
            'El Badari',
            'El Ghnayem',
            'El Qusya',
            'Elfath',
            'Manflout',
            'Sahel Selim',
            'Serfa'
        ),
        'EGMN' => array(
            'Abo Korkas',
            'Al Meniya',
            'Bani Mazar',
            'Dermwas',
            'Eladwa',
            'Malawi',
            'Matai',
            'Mghagha',
            'Minya',
            'Samaloot'
        ),
        'EGIS' => array(
            'Abo Sultan',
            'Abu Swer',
            'El Tal El Kebir',
            'Elsalhia Elgdida',
            'Fayed',
            'Ismailia',
            'Nfeesha',
            'Qantara Gharb',
            'Qantara Sharq',
            'Srabioom'
        ),
        'EGBH' => array(
            'Abou Al Matamer',
            'Abu Hummus',
            'Al Beheira',
            'Al Delengat',
            'Al Mahmoudiyah',
            'Al Rahmaniyah',
            'Damanhour',
            'Edfina',
            'Edko',
            'El Nubariyah',
            'Etay Al Barud',
            'Hosh Issa',
            'Kafr El Dawwar',
            'Kom Hamadah',
            'Rashid',
            'Shubrakhit',
            'Wadi Al Natroun'
        ),
        'EGASN' => array(
            'Abu Simbel',
            'Al Sad Al Aali',
            'Aswan',
            'Draw',
            'Edfo',
            'El Klabsha',
            'Kom Ombo',
            'Markaz Naser',
            'Nasr Elnoba'
        ),
        'EGKN' => array(
            'Abu Tesht',
            'Deshna',
            'Farshoot',
            'Naga Hamadi',
            'Naqada',
            'Qena',
            'Qoos'
        ),
        'EGKB' => array(
            'Abu Zaabal',
            'Al Khanka',
            'Al Shareaa Al Gadid',
            'Bahteem',
            'Banha',
            'El Kanater EL Khayrya',
            'El Khsos',
            'El Oboor',
            'El Qalag',
            'Kafr Shokr',
            'Meet Nama',
            'Mostorod',
            'Om Bayoumi',
            'Orabi',
            'Qaha',
            'Qalyoob',
            'Qalyubia',
            'Sheben Alkanater',
            'Shoubra Alkhema',
            'Tookh'
        ),
        'EGKB' => array(
            'Aga',
            'Al Daqahliya',
            'Al Mansoura',
            'Belqas',
            'Dekernes',
            'El Sinblaween',
            'Manzala',
            'Meet Ghamr',
            'Menit El Nasr',
            'Nabroo',
            'Shrbeen',
            'Talkha'
        ),
        'EGBNS' => array(
            'Ahnaseaa',
            'Bani Souaif',
            'Bebaa',
            'El Fashn',
            'El Korimat',
            'El Wastaa',
            'Naser',
            'New Bani Souaif',
            'Smostaa'
        ),
        'EGSUZ' => array(
            'Ain Al Sukhna',
            'Al Adabya',
            'Al Suez',
            'Ataka District',
            'El Arbeen District',
            'Elganaien District',
            'Suez'
        ),
        'EGSHG' => array(
            'Akhmem',
            'Dar Elsalam',
            'El Monshah',
            'Elbalyna',
            'Gerga',
            'Ghena',
            'Maragha',
            'Saqatlah',
            'Sohag',
            'Tahta',
            'Tema'
        ),
        'EGFYM' => array(
            'Al Fayoum',
            'Atsa',
            'Ebshoy',
            'El Aagamen',
            'Kofooer Elniel',
            'Manshaa Abdalla',
            'Manshaa Elgamal',
            'New Fayoum',
            'Sanhoor',
            'Sersenaa',
            'Sonores',
            'Tameaa',
            'Youssef Sadek'
        ),
        'EGGH' => array(
            'Al Gharbia',
            'Al Mahala Al Kobra',
            'Alsanta',
            'Basyoon',
            'Kafr Alziat',
            'Qotoor',
            'Samanood',
            'Tanta',
            'Zefta'
        ),
        'EGMNF' => array(
            'Al Monufia',
            'Ashmoon',
            'Berket Al Sabei',
            'Menoof',
            'Quesna',
            'Sadat City',
            'Shebin El Koom',
            'Shohada',
            'Tala'
        ),
        'EGKFS' => array(
            'Al Riadh',
            'Balteem',
            'Bela',
            'Borollos',
            'Desouq',
            'Fooh',
            'Hamool',
            'Kafr El Sheikh',
            'Metobas',
            'Qeleen',
            'Seedy Salem'
        ),
        'EGDT' => array(
            'Al Zarkah',
            'Damietta',
            'Fareskor',
            'Kafr Saad',
            'New Damietta',
            'Ras El Bar'
        ),
        'EGLX' => array(
            'Armant Gharb',
            'Armant Sharq',
            'El Karnak',
            'El Korna',
            'Esnaa',
            'Luxor'
        ),
        'EGMT' => array(
            'El Alamein',
            'El Dabaa',
            'Marsa Matrooh',
            'Matrooh',
            'Sidi Abdel Rahman'
        ),
        'EGBA' => array(
            'Gouna',
            'Hurghada',
            'Marsa Alam',
            'Qouseir',
            'Ras Ghareb',
            'Red Sea',
            'Safaga'
        ),
        'EGPTS' => array(
            'Port Fouad',
            'Port Said',
            'Zohoor District'
        )
    );
