<?php
/**
 * Cities in California, United States
 * List generated from http://www.epictrip.com/Cities-in-California-places-l5.html
 */
global $cities;

$cities['US'] = array(
	'CA' => array(
		'Acampo',
		'Acton',
		'Adelanto',
		'Adin',
		'Agoura Hills',
		'Aguanga',
		'Ahwahnee',
		'Alameda',
		'Alamo',
		'Albany',
		'Albion',
		'Alderpoint',
		'Alhambra',
		'Aliso Viejo',
		'Alleghany',
		'Alpaugh',
		'Alpine',
		'Alta',
		'Altadena',
		'Altaville',
		'Alturas',
		'Alviso',
		'Amador City',
		'Amboy',
		'American Canyon',
		'Anaheim',
		'Anderson',
		'Angels Camp',
		'Angelus Oaks',
		'Angwin',
		'Annapolis',
		'Antelope',
		'Antioch',
		'Anza',
		'Apple Valley',
		'Applegate',
		'Aptos',
		'Arbuckle',
		'Arcadia',
		'Arcata',
		'Armona',
		'Arnold',
		'Aromas',
		'Arroyo Grande',
		'Artesia',
		'Artois',
		'Arvin',
		'Atascadero',
		'Atherton',
		'Atwater',
		'Atwood',
		'Auberry',
		'Auburn',
		'Avalon',
		'Avenal',
		'Avery',
		'Avila Beach',
		'Azusa',
		'Badger',
		'Baker',
		'Bakersfield',
		'Baldwin Park',
		'Ballard',
		'Ballico',
		'Ballona Wetlands',
		'Bangor',
		'Banning',
		'Bard',
		'Barstow',
		'Bass Lake',
		'Bayside',
		'Beale Afb',
		'Beaumont',
		'Beckwourth',
		'Belden',
		'Bell',
		'Bell Gardens',
		'Bella Vista',
		'Bellflower',
		'Belmont',
		'Belvedere Tiburon',
		'Ben Lomond',
		'Benicia',
		'Benton',
		'Berkeley',
		'Bermuda Dunes',
		'Berry Creek',
		'Bethel Island',
		'Beverly Hills',
		'Bieber',
		'Big Bar',
		'Big Bear City',
		'Big Bear Lake',
		'Big Bend',
		'Big Creek',
		'Big Oak Flat',
		'Big Pine',
		'Big Sur',
		'Biggs',
		'Biola',
		'Birds Landing',
		'Bishop',
		'Blairsden-Graeagle',
		'Blocksburg',
		'Bloomington',
		'Blue Jay',
		'Blue Lake',
		'Blythe',
		'Bodega',
		'Bodega Bay',
		'Bodfish',
		'Bolinas',
		'Bonita',
		'Bonsall',
		'Boonville',
		'Boron',
		'Borrego Springs',
		'Boulder Creek',
		'Boulevard',
		'Boyes Hot Springs',
		'Bradley',
		'Brandeis',
		'Branscomb',
		'Brawley',
		'Brea',
		'Brentwood',
		'Bridgeport',
		'Bridgeville',
		'Brisbane',
		'Brockway',
		'Brookdale',
		'Brooks',
		'Browns Valley',
		'Brownsville',
		'Bryn Mawr',
		'Buellton',
		'Buena Park',
		'Burbank',
		'Burlingame',
		'Burney',
		'Burnt Ranch',
		'Burrel',
		'Burson',
		'Butte City',
		'Buttonwillow',
		'Byron',
		'Cabazon',
		'Calabasas',
		'Calexico',
		'Caliente',
		'California City',
		'California Hot Springs',
		'Calimesa',
		'Calipatria',
		'Calistoga',
		'Callahan',
		'Calpella',
		'Calpine',
		'Camarillo',
		'Cambria',
		'Cameron Park',
		'Camino',
		'Camp Meeker',
		'Camp Nelson',
		'Camp Pendleton',
		'Campbell',
		'Campo',
		'Campo Seco',
		'Camptonville',
		'Canby',
		'Canoga Park',
		'Cantil',
		'Cantua Creek',
		'Canyon',
		'Canyon Country',
		'Canyondam',
		'Capay',
		'Capistrano Beach',
		'Capitola',
		'Cardiff By The Sea',
		'Carlotta',
		'Carlsbad',
		'Carmel',
		'Carmel Valley',
		'Carmichael',
		'Carnelian Bay',
		'Carpinteria',
		'Carson',
		'Caruthers',
		'Casmalia',
		'Caspar',
		'Cassel',
		'Castaic',
		'Castella',
		'Castro Valley',
		'Castroville',
		'Catalina Island',
		'Cathedral City',
		'Catheys Valley',
		'Cayucos',
		'Cazadero',
		'Cedar Glen',
		'Cedar Ridge',
		'Cedarpines Park',
		'Cedarville',
		'Ceres',
		'Cerritos',
		'Challenge',
		'Chatsworth',
		'Chester',
		'Chicago Park',
		'Chico',
		'Chilcoot',
		'Chinese Camp',
		'Chino',
		'Chino Hills',
		'Chowchilla',
		'Chualar',
		'Chula Vista',
		'Cima',
		'Citrus Heights',
		'City Of Industry',
		'Claremont',
		'Clarksburg',
		'Clayton',
		'Clearlake',
		'Clearlake Oaks',
		'Clearlake Park',
		'Clements',
		'Clio',
		'Clipper Mills',
		'Cloverdale',
		'Clovis',
		'Coachella',
		'Coalinga',
		'Coarsegold',
		'Cobb',
		'Coleville',
		'Colfax',
		'College City',
		'Coloma',
		'Colton',
		'Columbia',
		'Colusa',
		'Commerce',
		'Comptche',
		'Compton',
		'Concord',
		'Cool',
		'Copperopolis',
		'Corcoran',
		'Corning',
		'Corona',
		'Corona del Mar',
		'Coronado',
		'Corte Madera',
		'Costa Mesa',
		'Cotati',
		'Cottonwood',
		'Coulterville',
		'Courtland',
		'Covelo',
		'Covina',
		'Coyote',
		'Crescent City',
		'Crescent Mills',
		'Cressey',
		'Crest Park',
		'Crestline',
		'Creston',
		'Crockett',
		'Crows Landing',
		'Culver City',
		'Cupertino',
		'Cutler',
		'Cutten',
		'Cypress',
		'Daggett',
		'Daly City',
		'Dana Point',
		'Danville',
		'Dardanelle',
		'Darwin',
		'Davenport',
		'Davis',
		'Davis Creek',
		'Death Valley',
		'Deer Park',
		'Del Mar',
		'Del Rey',
		'Delano',
		'Delhi',
		'Denair',
		'Descanso',
		'Desert Center',
		'Desert Hot Springs',
		'Diablo',
		'Diamond Bar',
		'Diamond Springs',
		'Dillon Beach',
		'Dinuba',
		'Dixon',
		'Dobbins',
		'Dorrington',
		'Dorris',
		'Dos Palos',
		'Dos Rios',
		'Douglas City',
		'Douglas Flat',
		'Downey',
		'Downieville',
		'Doyle',
		'Drytown',
		'Duarte',
		'Dublin',
		'Ducor',
		'Dulzura',
		'Duncans Mills',
		'Dunlap',
		'Dunnigan',
		'Dunsmuir',
		'Durham',
		'Dutch Flat',
		'Eagleville',
		'Earlimart',
		'Earp',
		'East Irvine',
		'Echo Lake',
		'Edison',
		'Edwards',
		'El Cajon',
		'El Centro',
		'El Cerrito',
		'El Dorado',
		'El Dorado Hills',
		'El Granada',
		'El Macero',
		'El Monte',
		'El Nido',
		'El Portal',
		'El Segundo',
		'El Sobrante',
		'El Toro',
		'El Verano',
		'Eldridge',
		'Elk',
		'Elk Creek',
		'Elk Grove',
		'Elmira',
		'Elverta',
		'Emeryville',
		'Emigrant Gap',
		'Empire',
		'Encinitas',
		'Encino',
		'Escalon',
		'Escondido',
		'Esparto',
		'Essex',
		'Etna',
		'Eureka',
		'Exeter',
		'Fair Oaks',
		'Fairfax',
		'Fairfield',
		'Fall River Mills',
		'Fallbrook',
		'Farmersville',
		'Farmington',
		'Fawnskin',
		'Feather Falls',
		'Fellows',
		'Felton',
		'Ferndale',
		'Fiddletown',
		'Fields Landing',
		'Fillmore',
		'Finley',
		'Firebaugh',
		'Fish Camp',
		'Five Points',
		'Floriston',
		'Flournoy',
		'Folsom',
		'Fontana',
		'Foothill Ranch',
		'Forbestown',
		'Forest Falls',
		'Froest Knolls',
		'Forest Ranch',
		'Foresthill',
		'Forestville',
		'Forks Of Salmon',
		'Fort Bidwell',
		'Fort Bragg',
		'Fort Dick',
		'Fort Irwin',
		'Fort Jones',
		'Fortuna',
		'Foster City',
		'Fountain Valley',
		'Fowler',
		'Frazier Park',
		'Freedom',
		'Fremont',
		'French Camp',
		'French Gulch',
		'Fresno',
		'Friant',
		'Fullerton',
		'Fulton',
		'Galt',
		'Garberville',
		'Garden Grove',
		'Garden Valley',
		'Gardena',
		'Gasquet',
		'Gazelle',
		'Georgetown',
		'Gerber',
		'Geyserville',
		'Gilroy',
		'Glen Ellen',
		'Glencoe',
		'Glendale',
		'Glendora',
		'Glenhaven',
		'Glenn',
		'Glennville',
		'Gold River',
		'Gold Run',
		'Goleta',
		'Gonzales',
		'Goodyears Bar',
		'Gorman',
		'Goshen',
		'Graeagle',
		'Granada Hills',
		'Grand Terrace',
		'Granite Bay',
		'Grass Valley',
		'Graton',
		'Green Valley Lake',
		'Greenbrae',
		'Greenfield',
		'Greenview',
		'Greenville',
		'Greenwood',
		'Grenada',
		'Gridley',
		'Grimes',
		'Grizzly Flats',
		'Groveland',
		'Grover Beach',
		'Guadalupe',
		'Gualala',
		'Guasti',
		'Guatay',
		'Guerneville',
		'Guinda',
		'Gustine',
		'Hacienda Heights',
		'Half Moon Bay',
		'Hamilton City',
		'Hanford',
		'Happy Camp',
		'Harbor City',
		'Harmony',
		'Hat Creek',
		'Hathaway Pines',
		'Hawaiian Gardens',
		'Hawthorne',
		'Hayfork',
		'Hayward',
		'Healdsburg',
		'Heber',
		'Helendale',
		'Helm',
		'Hemet',
		'Herald',
		'Hercules',
		'Herlong',
		'Hermosa Beach',
		'Hesperia',
		'Hickman',
		'Highland',
		'Hilmar',
		'Hinkley',
		'Hollister',
		'Hollywood',
		'Holt',
		'Holtville',
		'Holy City',
		'Homeland',
		'Homewood',
		'Honeydew',
		'Hood',
		'Hoopa',
		'Hope Valley',
		'Hopland',
		'Hornbrook',
		'Hornitos',
		'Hughson',
		'Hume',
		'Huntington Beach',
		'Huntington Park',
		'Huron',
		'Hyampom',
		'Hydesville',
		'Idyllwild',
		'Igo',
		'Imperial',
		'Imperial Beach',
		'Independence',
		'Indian Wells',
		'Indio',
		'Inglewood',
		'Inverness',
		'Inyokern',
		'Ione',
		'Irvine',
		'Isleton',
		'Ivanhoe',
		'Jackson',
		'Jacumba',
		'Jamestown',
		'Jamul',
		'Janesville',
		'Jenner',
		'Johannesburg',
		'Jolon',
		'Joshua Tree',
		'Julian',
		'Junction City',
		'June Lake',
		'Kaweah',
		'Keeler',
		'Keene',
		'Kelseyville',
		'Kentfield',
		'Kenwood',
		'Kerman',
		'Kernville',
		'Kettleman City',
		'Keyes',
		'King City',
		'Kings Beach',
		'Kings Canyon National Pk',
		'Kings Canyon Natl Park',
		'Kingsburg',
		'Kirkwood',
		'Kit Carson',
		'Klamath',
		'Klamath River',
		'Kneeland',
		'Knights Landing',
		'Knightsen',
		'Korbel',
		'Kyburz',
		'La Canada Flintridge',
		'La Crescenta',
		'La Grange',
		'La Habra',
		'La Honda',
		'La Jolla',
		'La Mesa',
		'La Mirada',
		'La Palma',
		'La Puente',
		'La Quinta',
		'La Verne',
		'Ladera Ranch',
		'Lafayette',
		'Laguna Beach',
		'Laguna Hills',
		'Laguna Niguel',
		'Laguna Woods',
		'Lagunitas',
		'Lake Arrowhead',
		'Lake City',
		'Lake Elsinore',
		'Lake Forest',
		'Lake Hughes',
		'Lake Isabella',
		'Lake Shore',
		'Lakehead',
		'Lakeport',
		'Lakeshore',
		'Lakeside',
		'Lakewood',
		'Lamont',
		'Lancaster',
		'Landers',
		'Larkspur',
		'Lathrop',
		'Laton',
		'Lawndale',
		'Laytonville',
		'Le Grand',
		'Lebec',
		'Lee Vining',
		'Leggett',
		'Lemon Cove',
		'Lemon Grove',
		'Lemoore',
		'Lewiston',
		'Likely',
		'Lincoln',
		'Lincoln Acres',
		'Linden',
		'Lindsay',
		'Litchfield',
		'Little Lake',
		'Little River',
		'Littleriver',
		'Littlerock',
		'Live Oak',
		'Livermore',
		'Livingston',
		'Llano',
		'Lockeford',
		'Lockwood',
		'Lodi',
		'Loleta',
		'Loma Linda',
		'Loma Mar',
		'Lomita',
		'Lompoc',
		'Lone Pine',
		'Long Barn',
		'Long Beach',
		'Lookout',
		'Loomis',
		'Los Alamitos',
		'Los Alamos',
		'Los Altos',
		'Los Angeles',
		'Los Banos',
		'Los Gatos',
		'Los Molinos',
		'Los Olivos',
		'Los Osos',
		'Lost Hills',
		'Lotus',
		'Lower Lake',
		'Loyalton',
		'Lucerne',
		'Lucerne Valley',
		'Ludlow',
		'Lynwood',
		'Lyoth',
		'Lytle Creek',
		'Macdoel',
		'Mad River',
		'Madeline',
		'Madera',
		'Madison',
		'Magalia',
		'Malibu',
		'Mammoth Lakes',
		'Manchester',
		'Manhattan Beach',
		'Manteca',
		'Manton',
		'March Air Force Base',
		'Maricopa',
		'Marina',
		'Marina del Rey',
		'Mariposa',
		'Markleeville',
		'Marshall',
		'Martell',
		'Martinez',
		'Marysville',
		'Mather',
		'Maxwell',
		'Maywood',
		'Mc Farland',
		'Mc Kittrick',
		'McArthur',
		'Mcclellan',
		'McCloud',
		'McKinleyville',
		'Meadow Valley',
		'Meadow Vista',
		'Mecca',
		'Mendocino',
		'Mendota',
		'Menifee',
		'Menlo Park',
		'Mentone',
		'Merced',
		'Meridian',
		'Mi Wuk Village',
		'Mi-Wuk Village',
		'Middletown',
		'Midpines',
		'Midway City',
		'Milford',
		'Mill Creek',
		'Mill Valley',
		'Millbrae',
		'Millville',
		'Milpitas',
		'Mineral',
		'Mira Loma',
		'Miramonte',
		'Miranda',
		'Mission Hills',
		'Mission Viejo',
		'Moccasin',
		'Modesto',
		'Mojave',
		'Mokelumne Hill',
		'Mono Hot Springs',
		'Monrovia',
		'Montague',
		'Montara',
		'Montclair',
		'Monte Rio',
		'Montebello',
		'Montecito',
		'Monterey',
		'Monterey Park',
		'Montgomery Creek',
		'Montrose',
		'Moorpark',
		'Moraga',
		'Moreno Valley',
		'Morgan Hill',
		'Morongo Valley',
		'Morro Bay',
		'Moss Beach',
		'Moss Landing',
		'Mount Aukum',
		'Mount Hamilton',
		'Mount Hermon',
		'Mount Laguna',
		'Mount Shasta',
		'Mount Wilson',
		'Mountain Center',
		'Mountain Pass',
		'Mountain Ranch',
		'Mountain View',
		'Mt Baldy',
		'Muir Beach',
		'Murphys',
		'Murrieta',
		'Mussel Shoals',
		'Myers Flat',
		'Napa',
		'National City',
		'Navarro',
		'Needles',
		'Nelson',
		'Nevada City',
		'New Almaden',
		'New Cuyama',
		'Newark',
		'Newberry Springs',
		'Newbury Park',
		'Newcastle',
		'Newhall',
		'Newman',
		'Newport Beach',
		'Newport Coast',
		'Nicasio',
		'Nice',
		'Nicolaus',
		'Niland',
		'Nipomo',
		'Nipton',
		'Norco',
		'Norden',
		'North Fork',
		'North Highlands',
		'North Hills',
		'North Hollywood',
		'North Palm Springs',
		'North San Juan',
		'Northridge',
		'Norwalk',
		'Novato',
		'Nubieber',
		'Nuevo',
		'O Neals',
		'Oak Park',
		'Oak Run',
		'Oak View',
		'Oakdale',
		'Oakhurst',
		'Oakland',
		'Oakley',
		'Oakville',
		'Obrien',
		'Occidental',
		'Oceano',
		'Oceanside',
		'Ocotillo',
		'Ojai',
		'Olancha',
		'Old Station',
		'Olema',
		'Olivehurst',
		'Olympic Valley',
		'Ontario',
		'Onyx',
		'Orange',
		'Orange Cove',
		'Orangevale',
		'Orcutt',
		'Oregon House',
		'Orick',
		'Orinda',
		'Orland',
		'Orleans',
		'Oro Grande',
		'Orosi',
		'Oroville',
		'Oxnard',
		'Pacific Grove',
		'Pacific Palisades',
		'Pacifica',
		'Pacoima',
		'Paicines',
		'Pala',
		'Palermo',
		'Palm Desert',
		'Palm Springs',
		'Palmdale',
		'Palo Alto',
		'Palo Cedro',
		'Palo Verde',
		'Palomar Mountain',
		'Palos Verdes Peninsula',
		'Panorama City',
		'Paradise',
		'Paramount',
		'Parker Dam',
		'Parlier',
		'Pasadena',
		'Paskenta',
		'Paso Robles',
		'Patterson',
		'Patton',
		'Pauma Valley',
		'Paynes Creek',
		'Pearblossom',
		'Pebble Beach',
		'Penn Valley',
		'Penngrove',
		'Penryn',
		'Perris',
		'Pescadero',
		'Petaluma',
		'Petrolia',
		'Phelan',
		'Phillipsville',
		'Philo',
		'Pico Rivera',
		'Piedmont',
		'Piedra',
		'Piercy',
		'Pilot Hill',
		'Pine Grove',
		'Pine Valley',
		'Pinecrest',
		'Pinole',
		'Pinon Hills',
		'Pioneer',
		'Pioneertown',
		'Piru',
		'Pismo Beach',
		'Pittsburg',
		'Pixley',
		'Placentia',
		'Placerville',
		'Planada',
		'Platina',
		'Playa del Rey',
		'Pleasant Grove',
		'Pleasant Hill',
		'Pleasanton',
		'Plymouth',
		'Point Arena',
		'Point Mugu Nawc',
		'Point Reyes Station',
		'Pollock Pines',
		'Pomona',
		'Pope Valley',
		'Port Costa',
		'Port Hueneme',
		'Port Hueneme Cbc Base',
		'Porterville',
		'Portola',
		'Portola Valley',
		'Posey',
		'Potrero',
		'Potter Valley',
		'Poway',
		'Prather',
		'Princeton',
		'Proberta',
		'Quincy',
		'Rackerby',
		'Rail Road Flat',
		'Raisin',
		'Ramona',
		'Ranchita',
		'Rancho Cordova',
		'Rancho Cucamonga',
		'Rancho Mirage',
		'Rancho Palos Verdes',
		'Rancho Santa Fe',
		'Rancho Santa Margarita',
		'Randsburg',
		'Ravendale',
		'Raymond',
		'Red Bluff',
		'Red Mountain',
		'Redcrest',
		'Redding',
		'Redlands',
		'Redondo Beach',
		'Redway',
		'Redwood City',
		'Redwood Estates',
		'Redwood Valley',
		'Reedley',
		'Represa',
		'Rescue',
		'Reseda',
		'Rialto',
		'Richgrove',
		'Richmond',
		'Richvale',
		'Ridgecrest',
		'Rimforest',
		'Rio Dell',
		'Rio Linda',
		'Rio Nido',
		'Rio Oso',
		'Rio Vista',
		'Ripon',
		'River Pines',
		'Riverbank',
		'Riverdale',
		'Riverside',
		'Robbins',
		'Rocklin',
		'Rodeo',
		'Rohnert Park',
		'Rosamond',
		'Rosemead',
		'Roseville',
		'Ross',
		'Rough and Ready',
		'Round Mountain',
		'Rowland Heights',
		'Rumsey',
		'Running Springs',
		'Rutherford',
		'Ryde',
		'Sacramento',
		'Salida',
		'Salinas',
		'Salton City',
		'Salyer',
		'Samoa',
		'San Andreas',
		'San Anselmo',
		'San Ardo',
		'San Bernardino',
		'San Bruno',
		'San Carlos',
		'San Clemente',
		'San Diego',
		'San Dimas',
		'San Fernando',
		'San Francisco',
		'San Gabriel',
		'San Geronimo',
		'San Gregorio',
		'San Jacinto',
		'San Joaquin',
		'San Jose',
		'San Juan Bautista',
		'San Juan Capistrano',
		'San Leandro',
		'San Lorenzo',
		'San Lucas',
		'San Luis Obispo',
		'San Luis Rey',
		'San Marcos',
		'San Marino',
		'San Martin',
		'San Mateo',
		'San Miguel',
		'San Pablo',
		'San Pedro',
		'San Quentin',
		'San Rafael',
		'San Ramon',
		'San Simeon',
		'San Ysidro',
		'Sanger',
		'Santa Ana',
		'Santa Barbara',
		'Santa Clara',
		'Santa Clarita',
		'Santa Cruz',
		'Santa Fe Springs',
		'Santa Margarita',
		'Santa Maria',
		'Santa Monica',
		'Santa Nella',
		'Santa Paula',
		'Santa Rita Park',
		'Santa Rosa',
		'Santa Ynez',
		'Santa Ysabel',
		'Santee',
		'Saratoga',
		'Sausalito',
		'Scotia',
		'Scott Bar',
		'Scotts Valley',
		'Seal Beach',
		'Seaside',
		'Sebastopol',
		'Seeley',
		'Seiad Valley',
		'Selma',
		'Sepulveda',
		'Sequoia National Park',
		'Shafter',
		'Shandon',
		'Shasta',
		'Shasta Lake',
		'Shaver Lake',
		'Sheep Ranch',
		'Shell Beach',
		'Sheridan',
		'Sherman Oaks',
		'Shingle Springs',
		'Shingletown',
		'Shoshone',
		'Sierra City',
		'Sierra Madre',
		'Sierraville',
		'Signal Hill',
		'Silicon Valley',
		'Silverado',
		'Simi Valley',
		'Skyforest',
		'Sloughhouse',
		'Smartville',
		'Smith River',
		'Snelling',
		'Soda Springs',
		'Solana Beach',
		'Soledad',
		'Solvang',
		'Somerset',
		'Somes Bar',
		'Somis',
		'Sonoma',
		'Sonora',
		'Soquel',
		'Soulsbyville',
		'South Dos Palos',
		'South El Monte',
		'South Gate',
		'South Lake Tahoe',
		'South Pasadena',
		'South San Francisco',
		'Spreckels',
		'Spring Valley',
		'Springville',
		'Squaw Valley',
		'St Helena',
		'Standard',
		'Standish',
		'Stanford',
		'Stanton',
		'Stevenson Ranch',
		'Stevinson',
		'Stewarts Point',
		'Stinson Beach',
		'Stirling City',
		'Stockton',
		'Stonyford',
		'Storrie',
		'Stratford',
		'Strathmore',
		'Strawberry',
		'Strawberry Valley',
		'Studio City',
		'Sugarloaf',
		'Suisun City',
		'Sultana',
		'Summerland',
		'Sun City',
		'Sun Valley',
		'Sunland',
		'Sunnyvale',
		'Sunol',
		'Sunset Beach',
		'Surfside',
		'Susanville',
		'Sutter',
		'Sutter Creek',
		'Sylmar',
		'Taft',
		'Tahoe City',
		'Tahoe Vista',
		'Tahoma',
		'Talmage',
		'Tarzana',
		'Taylorsville',
		'Tecate',
		'Tecopa',
		'Tehachapi',
		'Tehama',
		'Temecula',
		'Temple City',
		'Templeton',
		'Termo',
		'Terra Bella',
		'The Sea Ranch',
		'Thermal',
		'Thornton',
		'Thousand Oaks',
		'Thousand Palms',
		'Three Rivers',
		'Tiburon',
		'Tipton',
		'Tollhouse',
		'Toluca Lake',
		'Tomales',
		'Topanga',
		'Topaz',
		'Torrance',
		'Trabuco Canyon',
		'Tracy',
		'Tranquillity',
		'Traver',
		'Travis Afb',
		'Tres Pinos',
		'Trinidad',
		'Trinity Center',
		'Trona',
		'Truckee',
		'Tujunga',
		'Tulare',
		'Tulelake',
		'Tuolumne',
		'Tupman',
		'Turlock',
		'Tustin',
		'Twain',
		'Twain Harte',
		'Twentynine Palms',
		'Twin Bridges',
		'Twin Peaks',
		'Ukiah',
		'Union City',
		'Universal City',
		'Upland',
		'Upper Lake',
		'Vacaville',
		'Valencia',
		'Vallecito',
		'Vallejo',
		'Valley Center',
		'Valley Ford',
		'Valley Springs',
		'Valley Village',
		'Valyermo',
		'Van Nuys',
		'Venice',
		'Ventura',
		'Verdugo City',
		'Vernalis',
		'Victor',
		'Victorville',
		'Vidal',
		'Villa Grande',
		'Villa Park',
		'Vina',
		'Vineburg',
		'Vinton',
		'Visalia',
		'Vista',
		'Volcano',
		'Wallace',
		'Walnut',
		'Walnut Creek',
		'Walnut Grove',
		'Warner Springs',
		'Wasco',
		'Washington',
		'Waterford',
		'Watsonville',
		'Waukena',
		'Weaverville',
		'Weed',
		'Weimar',
		'Weldon',
		'Wendel',
		'Weott',
		'West Covina',
		'West Hills',
		'West Hollywood',
		'West Los Angeles',
		'West Point',
		'West Sacramento',
		'Westlake Village',
		'Westley',
		'Westminster',
		'Westmorland',
		'Westport',
		'Westwood',
		'Wheatland',
		'Whiskeytown',
		'White Water',
		'Whitethorn',
		'Whitmore',
		'Whittier',
		'Wildomar',
		'Williams',
		'Willits',
		'Willow Creek',
		'Willows',
		'Wilmington',
		'Wilseyville',
		'Wilton',
		'Winchester',
		'Windsor',
		'Winnetka',
		'Winterhaven',
		'Winters',
		'Winton',
		'Wishon',
		'Witter Springs',
		'Wofford Heights',
		'Woodacre',
		'Woodbridge',
		'Woodlake',
		'Woodland',
		'Woodland Hills',
		'Woody',
		'Wrightwood',
		'Yermo',
		'Yettem',
		'Yolo',
		'Yorba Linda',
		'Yorkville',
		'Yosemite National Park',
		'Yountville',
		'Yreka',
		'Yuba City',
		'Yucaipa',
		'Yucca Valley',
		'Zamora',
		'Zenia'
	)
);
