<?php

if (!defined('ABSPATH')) exit;

// Generated by wp-scoper. Do not edit.

spl_autoload_register(function ($class) {
    static $classmap = null;

    if ($classmap === null) {
        $classmap = require __DIR__ . '/autoload-classmap.php';
    }

    if (isset($classmap[$class])) {
        require __DIR__ . '/' . $classmap[$class];
    }
});

// PSR-4 autoload (host project)
spl_autoload_register(function ($class) {
    static $psr4Map = [
        'WPParsidate\\' => __DIR__ . '/../inc',
    ];

    foreach ($psr4Map as $prefix => $baseDir) {
        $len = strlen($prefix);
        if (strncmp($prefix, $class, $len) !== 0) {
            continue;
        }

        $relativeClass = substr($class, $len);
        $file = $baseDir . '/' . str_replace('\\', '/', $relativeClass) . '.php';

        if (file_exists($file)) {
            require $file;
            return;
        }
    }
});

// Files autoload
require_once __DIR__ . '/symfony/polyfill-php80/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php81/bootstrap.php';
require_once __DIR__ . '/symfony/polyfill-php83/bootstrap.php';
